//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: app/observatory/command/command.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Xray_Core_App_Observatory_Command_ObservatoryServiceClient`, then call methods of this protocol to make API calls.
public protocol Xray_Core_App_Observatory_Command_ObservatoryServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Xray_Core_App_Observatory_Command_ObservatoryServiceClientInterceptorFactoryProtocol? { get }

  func getOutboundStatus(
    _ request: Xray_Core_App_Observatory_Command_GetOutboundStatusRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Xray_Core_App_Observatory_Command_GetOutboundStatusRequest, Xray_Core_App_Observatory_Command_GetOutboundStatusResponse>
}

extension Xray_Core_App_Observatory_Command_ObservatoryServiceClientProtocol {
  public var serviceName: String {
    return "xray.core.app.observatory.command.ObservatoryService"
  }

  /// Unary call to GetOutboundStatus
  ///
  /// - Parameters:
  ///   - request: Request to send to GetOutboundStatus.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func getOutboundStatus(
    _ request: Xray_Core_App_Observatory_Command_GetOutboundStatusRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Xray_Core_App_Observatory_Command_GetOutboundStatusRequest, Xray_Core_App_Observatory_Command_GetOutboundStatusResponse> {
    return self.makeUnaryCall(
      path: Xray_Core_App_Observatory_Command_ObservatoryServiceClientMetadata.Methods.getOutboundStatus.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetOutboundStatusInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Xray_Core_App_Observatory_Command_ObservatoryServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Xray_Core_App_Observatory_Command_ObservatoryServiceNIOClient")
public final class Xray_Core_App_Observatory_Command_ObservatoryServiceClient: Xray_Core_App_Observatory_Command_ObservatoryServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Xray_Core_App_Observatory_Command_ObservatoryServiceClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: Xray_Core_App_Observatory_Command_ObservatoryServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the xray.core.app.observatory.command.ObservatoryService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Xray_Core_App_Observatory_Command_ObservatoryServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct Xray_Core_App_Observatory_Command_ObservatoryServiceNIOClient: Xray_Core_App_Observatory_Command_ObservatoryServiceClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Xray_Core_App_Observatory_Command_ObservatoryServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the xray.core.app.observatory.command.ObservatoryService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Xray_Core_App_Observatory_Command_ObservatoryServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Xray_Core_App_Observatory_Command_ObservatoryServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Xray_Core_App_Observatory_Command_ObservatoryServiceClientInterceptorFactoryProtocol? { get }

  func makeGetOutboundStatusCall(
    _ request: Xray_Core_App_Observatory_Command_GetOutboundStatusRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Xray_Core_App_Observatory_Command_GetOutboundStatusRequest, Xray_Core_App_Observatory_Command_GetOutboundStatusResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Xray_Core_App_Observatory_Command_ObservatoryServiceAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Xray_Core_App_Observatory_Command_ObservatoryServiceClientMetadata.serviceDescriptor
  }

  public var interceptors: Xray_Core_App_Observatory_Command_ObservatoryServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeGetOutboundStatusCall(
    _ request: Xray_Core_App_Observatory_Command_GetOutboundStatusRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Xray_Core_App_Observatory_Command_GetOutboundStatusRequest, Xray_Core_App_Observatory_Command_GetOutboundStatusResponse> {
    return self.makeAsyncUnaryCall(
      path: Xray_Core_App_Observatory_Command_ObservatoryServiceClientMetadata.Methods.getOutboundStatus.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetOutboundStatusInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Xray_Core_App_Observatory_Command_ObservatoryServiceAsyncClientProtocol {
  public func getOutboundStatus(
    _ request: Xray_Core_App_Observatory_Command_GetOutboundStatusRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Xray_Core_App_Observatory_Command_GetOutboundStatusResponse {
    return try await self.performAsyncUnaryCall(
      path: Xray_Core_App_Observatory_Command_ObservatoryServiceClientMetadata.Methods.getOutboundStatus.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetOutboundStatusInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Xray_Core_App_Observatory_Command_ObservatoryServiceAsyncClient: Xray_Core_App_Observatory_Command_ObservatoryServiceAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Xray_Core_App_Observatory_Command_ObservatoryServiceClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Xray_Core_App_Observatory_Command_ObservatoryServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

public protocol Xray_Core_App_Observatory_Command_ObservatoryServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'getOutboundStatus'.
  func makeGetOutboundStatusInterceptors() -> [ClientInterceptor<Xray_Core_App_Observatory_Command_GetOutboundStatusRequest, Xray_Core_App_Observatory_Command_GetOutboundStatusResponse>]
}

public enum Xray_Core_App_Observatory_Command_ObservatoryServiceClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "ObservatoryService",
    fullName: "xray.core.app.observatory.command.ObservatoryService",
    methods: [
      Xray_Core_App_Observatory_Command_ObservatoryServiceClientMetadata.Methods.getOutboundStatus,
    ]
  )

  public enum Methods {
    public static let getOutboundStatus = GRPCMethodDescriptor(
      name: "GetOutboundStatus",
      path: "/xray.core.app.observatory.command.ObservatoryService/GetOutboundStatus",
      type: GRPCCallType.unary
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
public protocol Xray_Core_App_Observatory_Command_ObservatoryServiceProvider: CallHandlerProvider {
  var interceptors: Xray_Core_App_Observatory_Command_ObservatoryServiceServerInterceptorFactoryProtocol? { get }

  func getOutboundStatus(request: Xray_Core_App_Observatory_Command_GetOutboundStatusRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Xray_Core_App_Observatory_Command_GetOutboundStatusResponse>
}

extension Xray_Core_App_Observatory_Command_ObservatoryServiceProvider {
  public var serviceName: Substring {
    return Xray_Core_App_Observatory_Command_ObservatoryServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "GetOutboundStatus":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Xray_Core_App_Observatory_Command_GetOutboundStatusRequest>(),
        responseSerializer: ProtobufSerializer<Xray_Core_App_Observatory_Command_GetOutboundStatusResponse>(),
        interceptors: self.interceptors?.makeGetOutboundStatusInterceptors() ?? [],
        userFunction: self.getOutboundStatus(request:context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Xray_Core_App_Observatory_Command_ObservatoryServiceAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Xray_Core_App_Observatory_Command_ObservatoryServiceServerInterceptorFactoryProtocol? { get }

  func getOutboundStatus(
    request: Xray_Core_App_Observatory_Command_GetOutboundStatusRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Xray_Core_App_Observatory_Command_GetOutboundStatusResponse
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Xray_Core_App_Observatory_Command_ObservatoryServiceAsyncProvider {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Xray_Core_App_Observatory_Command_ObservatoryServiceServerMetadata.serviceDescriptor
  }

  public var serviceName: Substring {
    return Xray_Core_App_Observatory_Command_ObservatoryServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  public var interceptors: Xray_Core_App_Observatory_Command_ObservatoryServiceServerInterceptorFactoryProtocol? {
    return nil
  }

  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "GetOutboundStatus":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Xray_Core_App_Observatory_Command_GetOutboundStatusRequest>(),
        responseSerializer: ProtobufSerializer<Xray_Core_App_Observatory_Command_GetOutboundStatusResponse>(),
        interceptors: self.interceptors?.makeGetOutboundStatusInterceptors() ?? [],
        wrapping: { try await self.getOutboundStatus(request: $0, context: $1) }
      )

    default:
      return nil
    }
  }
}

public protocol Xray_Core_App_Observatory_Command_ObservatoryServiceServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'getOutboundStatus'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetOutboundStatusInterceptors() -> [ServerInterceptor<Xray_Core_App_Observatory_Command_GetOutboundStatusRequest, Xray_Core_App_Observatory_Command_GetOutboundStatusResponse>]
}

public enum Xray_Core_App_Observatory_Command_ObservatoryServiceServerMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "ObservatoryService",
    fullName: "xray.core.app.observatory.command.ObservatoryService",
    methods: [
      Xray_Core_App_Observatory_Command_ObservatoryServiceServerMetadata.Methods.getOutboundStatus,
    ]
  )

  public enum Methods {
    public static let getOutboundStatus = GRPCMethodDescriptor(
      name: "GetOutboundStatus",
      path: "/xray.core.app.observatory.command.ObservatoryService/GetOutboundStatus",
      type: GRPCCallType.unary
    )
  }
}
