//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: app/log/command/config.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Xray_App_Log_Command_LoggerServiceClient`, then call methods of this protocol to make API calls.
public protocol Xray_App_Log_Command_LoggerServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Xray_App_Log_Command_LoggerServiceClientInterceptorFactoryProtocol? { get }

  func restartLogger(
    _ request: Xray_App_Log_Command_RestartLoggerRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Xray_App_Log_Command_RestartLoggerRequest, Xray_App_Log_Command_RestartLoggerResponse>
}

extension Xray_App_Log_Command_LoggerServiceClientProtocol {
  public var serviceName: String {
    return "xray.app.log.command.LoggerService"
  }

  /// Unary call to RestartLogger
  ///
  /// - Parameters:
  ///   - request: Request to send to RestartLogger.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func restartLogger(
    _ request: Xray_App_Log_Command_RestartLoggerRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Xray_App_Log_Command_RestartLoggerRequest, Xray_App_Log_Command_RestartLoggerResponse> {
    return self.makeUnaryCall(
      path: Xray_App_Log_Command_LoggerServiceClientMetadata.Methods.restartLogger.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRestartLoggerInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Xray_App_Log_Command_LoggerServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Xray_App_Log_Command_LoggerServiceNIOClient")
public final class Xray_App_Log_Command_LoggerServiceClient: Xray_App_Log_Command_LoggerServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Xray_App_Log_Command_LoggerServiceClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: Xray_App_Log_Command_LoggerServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the xray.app.log.command.LoggerService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Xray_App_Log_Command_LoggerServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct Xray_App_Log_Command_LoggerServiceNIOClient: Xray_App_Log_Command_LoggerServiceClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Xray_App_Log_Command_LoggerServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the xray.app.log.command.LoggerService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Xray_App_Log_Command_LoggerServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Xray_App_Log_Command_LoggerServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Xray_App_Log_Command_LoggerServiceClientInterceptorFactoryProtocol? { get }

  func makeRestartLoggerCall(
    _ request: Xray_App_Log_Command_RestartLoggerRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Xray_App_Log_Command_RestartLoggerRequest, Xray_App_Log_Command_RestartLoggerResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Xray_App_Log_Command_LoggerServiceAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Xray_App_Log_Command_LoggerServiceClientMetadata.serviceDescriptor
  }

  public var interceptors: Xray_App_Log_Command_LoggerServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeRestartLoggerCall(
    _ request: Xray_App_Log_Command_RestartLoggerRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Xray_App_Log_Command_RestartLoggerRequest, Xray_App_Log_Command_RestartLoggerResponse> {
    return self.makeAsyncUnaryCall(
      path: Xray_App_Log_Command_LoggerServiceClientMetadata.Methods.restartLogger.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRestartLoggerInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Xray_App_Log_Command_LoggerServiceAsyncClientProtocol {
  public func restartLogger(
    _ request: Xray_App_Log_Command_RestartLoggerRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Xray_App_Log_Command_RestartLoggerResponse {
    return try await self.performAsyncUnaryCall(
      path: Xray_App_Log_Command_LoggerServiceClientMetadata.Methods.restartLogger.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRestartLoggerInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Xray_App_Log_Command_LoggerServiceAsyncClient: Xray_App_Log_Command_LoggerServiceAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Xray_App_Log_Command_LoggerServiceClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Xray_App_Log_Command_LoggerServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

public protocol Xray_App_Log_Command_LoggerServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'restartLogger'.
  func makeRestartLoggerInterceptors() -> [ClientInterceptor<Xray_App_Log_Command_RestartLoggerRequest, Xray_App_Log_Command_RestartLoggerResponse>]
}

public enum Xray_App_Log_Command_LoggerServiceClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "LoggerService",
    fullName: "xray.app.log.command.LoggerService",
    methods: [
      Xray_App_Log_Command_LoggerServiceClientMetadata.Methods.restartLogger,
    ]
  )

  public enum Methods {
    public static let restartLogger = GRPCMethodDescriptor(
      name: "RestartLogger",
      path: "/xray.app.log.command.LoggerService/RestartLogger",
      type: GRPCCallType.unary
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
public protocol Xray_App_Log_Command_LoggerServiceProvider: CallHandlerProvider {
  var interceptors: Xray_App_Log_Command_LoggerServiceServerInterceptorFactoryProtocol? { get }

  func restartLogger(request: Xray_App_Log_Command_RestartLoggerRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Xray_App_Log_Command_RestartLoggerResponse>
}

extension Xray_App_Log_Command_LoggerServiceProvider {
  public var serviceName: Substring {
    return Xray_App_Log_Command_LoggerServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "RestartLogger":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Xray_App_Log_Command_RestartLoggerRequest>(),
        responseSerializer: ProtobufSerializer<Xray_App_Log_Command_RestartLoggerResponse>(),
        interceptors: self.interceptors?.makeRestartLoggerInterceptors() ?? [],
        userFunction: self.restartLogger(request:context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Xray_App_Log_Command_LoggerServiceAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Xray_App_Log_Command_LoggerServiceServerInterceptorFactoryProtocol? { get }

  func restartLogger(
    request: Xray_App_Log_Command_RestartLoggerRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Xray_App_Log_Command_RestartLoggerResponse
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Xray_App_Log_Command_LoggerServiceAsyncProvider {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Xray_App_Log_Command_LoggerServiceServerMetadata.serviceDescriptor
  }

  public var serviceName: Substring {
    return Xray_App_Log_Command_LoggerServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  public var interceptors: Xray_App_Log_Command_LoggerServiceServerInterceptorFactoryProtocol? {
    return nil
  }

  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "RestartLogger":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Xray_App_Log_Command_RestartLoggerRequest>(),
        responseSerializer: ProtobufSerializer<Xray_App_Log_Command_RestartLoggerResponse>(),
        interceptors: self.interceptors?.makeRestartLoggerInterceptors() ?? [],
        wrapping: { try await self.restartLogger(request: $0, context: $1) }
      )

    default:
      return nil
    }
  }
}

public protocol Xray_App_Log_Command_LoggerServiceServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'restartLogger'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeRestartLoggerInterceptors() -> [ServerInterceptor<Xray_App_Log_Command_RestartLoggerRequest, Xray_App_Log_Command_RestartLoggerResponse>]
}

public enum Xray_App_Log_Command_LoggerServiceServerMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "LoggerService",
    fullName: "xray.app.log.command.LoggerService",
    methods: [
      Xray_App_Log_Command_LoggerServiceServerMetadata.Methods.restartLogger,
    ]
  )

  public enum Methods {
    public static let restartLogger = GRPCMethodDescriptor(
      name: "RestartLogger",
      path: "/xray.app.log.command.LoggerService/RestartLogger",
      type: GRPCCallType.unary
    )
  }
}
