//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: app/proxyman/command/command.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Xray_App_Proxyman_Command_HandlerServiceClient`, then call methods of this protocol to make API calls.
public protocol Xray_App_Proxyman_Command_HandlerServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Xray_App_Proxyman_Command_HandlerServiceClientInterceptorFactoryProtocol? { get }

  func addInbound(
    _ request: Xray_App_Proxyman_Command_AddInboundRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Xray_App_Proxyman_Command_AddInboundRequest, Xray_App_Proxyman_Command_AddInboundResponse>

  func removeInbound(
    _ request: Xray_App_Proxyman_Command_RemoveInboundRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Xray_App_Proxyman_Command_RemoveInboundRequest, Xray_App_Proxyman_Command_RemoveInboundResponse>

  func alterInbound(
    _ request: Xray_App_Proxyman_Command_AlterInboundRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Xray_App_Proxyman_Command_AlterInboundRequest, Xray_App_Proxyman_Command_AlterInboundResponse>

  func listInbounds(
    _ request: Xray_App_Proxyman_Command_ListInboundsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Xray_App_Proxyman_Command_ListInboundsRequest, Xray_App_Proxyman_Command_ListInboundsResponse>

  func getInboundUsers(
    _ request: Xray_App_Proxyman_Command_GetInboundUserRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Xray_App_Proxyman_Command_GetInboundUserRequest, Xray_App_Proxyman_Command_GetInboundUserResponse>

  func getInboundUsersCount(
    _ request: Xray_App_Proxyman_Command_GetInboundUserRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Xray_App_Proxyman_Command_GetInboundUserRequest, Xray_App_Proxyman_Command_GetInboundUsersCountResponse>

  func addOutbound(
    _ request: Xray_App_Proxyman_Command_AddOutboundRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Xray_App_Proxyman_Command_AddOutboundRequest, Xray_App_Proxyman_Command_AddOutboundResponse>

  func removeOutbound(
    _ request: Xray_App_Proxyman_Command_RemoveOutboundRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Xray_App_Proxyman_Command_RemoveOutboundRequest, Xray_App_Proxyman_Command_RemoveOutboundResponse>

  func alterOutbound(
    _ request: Xray_App_Proxyman_Command_AlterOutboundRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Xray_App_Proxyman_Command_AlterOutboundRequest, Xray_App_Proxyman_Command_AlterOutboundResponse>

  func listOutbounds(
    _ request: Xray_App_Proxyman_Command_ListOutboundsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Xray_App_Proxyman_Command_ListOutboundsRequest, Xray_App_Proxyman_Command_ListOutboundsResponse>
}

extension Xray_App_Proxyman_Command_HandlerServiceClientProtocol {
  public var serviceName: String {
    return "xray.app.proxyman.command.HandlerService"
  }

  /// Unary call to AddInbound
  ///
  /// - Parameters:
  ///   - request: Request to send to AddInbound.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func addInbound(
    _ request: Xray_App_Proxyman_Command_AddInboundRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Xray_App_Proxyman_Command_AddInboundRequest, Xray_App_Proxyman_Command_AddInboundResponse> {
    return self.makeUnaryCall(
      path: Xray_App_Proxyman_Command_HandlerServiceClientMetadata.Methods.addInbound.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAddInboundInterceptors() ?? []
    )
  }

  /// Unary call to RemoveInbound
  ///
  /// - Parameters:
  ///   - request: Request to send to RemoveInbound.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func removeInbound(
    _ request: Xray_App_Proxyman_Command_RemoveInboundRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Xray_App_Proxyman_Command_RemoveInboundRequest, Xray_App_Proxyman_Command_RemoveInboundResponse> {
    return self.makeUnaryCall(
      path: Xray_App_Proxyman_Command_HandlerServiceClientMetadata.Methods.removeInbound.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRemoveInboundInterceptors() ?? []
    )
  }

  /// Unary call to AlterInbound
  ///
  /// - Parameters:
  ///   - request: Request to send to AlterInbound.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func alterInbound(
    _ request: Xray_App_Proxyman_Command_AlterInboundRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Xray_App_Proxyman_Command_AlterInboundRequest, Xray_App_Proxyman_Command_AlterInboundResponse> {
    return self.makeUnaryCall(
      path: Xray_App_Proxyman_Command_HandlerServiceClientMetadata.Methods.alterInbound.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAlterInboundInterceptors() ?? []
    )
  }

  /// Unary call to ListInbounds
  ///
  /// - Parameters:
  ///   - request: Request to send to ListInbounds.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func listInbounds(
    _ request: Xray_App_Proxyman_Command_ListInboundsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Xray_App_Proxyman_Command_ListInboundsRequest, Xray_App_Proxyman_Command_ListInboundsResponse> {
    return self.makeUnaryCall(
      path: Xray_App_Proxyman_Command_HandlerServiceClientMetadata.Methods.listInbounds.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListInboundsInterceptors() ?? []
    )
  }

  /// Unary call to GetInboundUsers
  ///
  /// - Parameters:
  ///   - request: Request to send to GetInboundUsers.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func getInboundUsers(
    _ request: Xray_App_Proxyman_Command_GetInboundUserRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Xray_App_Proxyman_Command_GetInboundUserRequest, Xray_App_Proxyman_Command_GetInboundUserResponse> {
    return self.makeUnaryCall(
      path: Xray_App_Proxyman_Command_HandlerServiceClientMetadata.Methods.getInboundUsers.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetInboundUsersInterceptors() ?? []
    )
  }

  /// Unary call to GetInboundUsersCount
  ///
  /// - Parameters:
  ///   - request: Request to send to GetInboundUsersCount.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func getInboundUsersCount(
    _ request: Xray_App_Proxyman_Command_GetInboundUserRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Xray_App_Proxyman_Command_GetInboundUserRequest, Xray_App_Proxyman_Command_GetInboundUsersCountResponse> {
    return self.makeUnaryCall(
      path: Xray_App_Proxyman_Command_HandlerServiceClientMetadata.Methods.getInboundUsersCount.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetInboundUsersCountInterceptors() ?? []
    )
  }

  /// Unary call to AddOutbound
  ///
  /// - Parameters:
  ///   - request: Request to send to AddOutbound.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func addOutbound(
    _ request: Xray_App_Proxyman_Command_AddOutboundRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Xray_App_Proxyman_Command_AddOutboundRequest, Xray_App_Proxyman_Command_AddOutboundResponse> {
    return self.makeUnaryCall(
      path: Xray_App_Proxyman_Command_HandlerServiceClientMetadata.Methods.addOutbound.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAddOutboundInterceptors() ?? []
    )
  }

  /// Unary call to RemoveOutbound
  ///
  /// - Parameters:
  ///   - request: Request to send to RemoveOutbound.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func removeOutbound(
    _ request: Xray_App_Proxyman_Command_RemoveOutboundRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Xray_App_Proxyman_Command_RemoveOutboundRequest, Xray_App_Proxyman_Command_RemoveOutboundResponse> {
    return self.makeUnaryCall(
      path: Xray_App_Proxyman_Command_HandlerServiceClientMetadata.Methods.removeOutbound.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRemoveOutboundInterceptors() ?? []
    )
  }

  /// Unary call to AlterOutbound
  ///
  /// - Parameters:
  ///   - request: Request to send to AlterOutbound.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func alterOutbound(
    _ request: Xray_App_Proxyman_Command_AlterOutboundRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Xray_App_Proxyman_Command_AlterOutboundRequest, Xray_App_Proxyman_Command_AlterOutboundResponse> {
    return self.makeUnaryCall(
      path: Xray_App_Proxyman_Command_HandlerServiceClientMetadata.Methods.alterOutbound.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAlterOutboundInterceptors() ?? []
    )
  }

  /// Unary call to ListOutbounds
  ///
  /// - Parameters:
  ///   - request: Request to send to ListOutbounds.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func listOutbounds(
    _ request: Xray_App_Proxyman_Command_ListOutboundsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Xray_App_Proxyman_Command_ListOutboundsRequest, Xray_App_Proxyman_Command_ListOutboundsResponse> {
    return self.makeUnaryCall(
      path: Xray_App_Proxyman_Command_HandlerServiceClientMetadata.Methods.listOutbounds.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListOutboundsInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Xray_App_Proxyman_Command_HandlerServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Xray_App_Proxyman_Command_HandlerServiceNIOClient")
public final class Xray_App_Proxyman_Command_HandlerServiceClient: Xray_App_Proxyman_Command_HandlerServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Xray_App_Proxyman_Command_HandlerServiceClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: Xray_App_Proxyman_Command_HandlerServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the xray.app.proxyman.command.HandlerService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Xray_App_Proxyman_Command_HandlerServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct Xray_App_Proxyman_Command_HandlerServiceNIOClient: Xray_App_Proxyman_Command_HandlerServiceClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Xray_App_Proxyman_Command_HandlerServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the xray.app.proxyman.command.HandlerService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Xray_App_Proxyman_Command_HandlerServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Xray_App_Proxyman_Command_HandlerServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Xray_App_Proxyman_Command_HandlerServiceClientInterceptorFactoryProtocol? { get }

  func makeAddInboundCall(
    _ request: Xray_App_Proxyman_Command_AddInboundRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Xray_App_Proxyman_Command_AddInboundRequest, Xray_App_Proxyman_Command_AddInboundResponse>

  func makeRemoveInboundCall(
    _ request: Xray_App_Proxyman_Command_RemoveInboundRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Xray_App_Proxyman_Command_RemoveInboundRequest, Xray_App_Proxyman_Command_RemoveInboundResponse>

  func makeAlterInboundCall(
    _ request: Xray_App_Proxyman_Command_AlterInboundRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Xray_App_Proxyman_Command_AlterInboundRequest, Xray_App_Proxyman_Command_AlterInboundResponse>

  func makeListInboundsCall(
    _ request: Xray_App_Proxyman_Command_ListInboundsRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Xray_App_Proxyman_Command_ListInboundsRequest, Xray_App_Proxyman_Command_ListInboundsResponse>

  func makeGetInboundUsersCall(
    _ request: Xray_App_Proxyman_Command_GetInboundUserRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Xray_App_Proxyman_Command_GetInboundUserRequest, Xray_App_Proxyman_Command_GetInboundUserResponse>

  func makeGetInboundUsersCountCall(
    _ request: Xray_App_Proxyman_Command_GetInboundUserRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Xray_App_Proxyman_Command_GetInboundUserRequest, Xray_App_Proxyman_Command_GetInboundUsersCountResponse>

  func makeAddOutboundCall(
    _ request: Xray_App_Proxyman_Command_AddOutboundRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Xray_App_Proxyman_Command_AddOutboundRequest, Xray_App_Proxyman_Command_AddOutboundResponse>

  func makeRemoveOutboundCall(
    _ request: Xray_App_Proxyman_Command_RemoveOutboundRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Xray_App_Proxyman_Command_RemoveOutboundRequest, Xray_App_Proxyman_Command_RemoveOutboundResponse>

  func makeAlterOutboundCall(
    _ request: Xray_App_Proxyman_Command_AlterOutboundRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Xray_App_Proxyman_Command_AlterOutboundRequest, Xray_App_Proxyman_Command_AlterOutboundResponse>

  func makeListOutboundsCall(
    _ request: Xray_App_Proxyman_Command_ListOutboundsRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Xray_App_Proxyman_Command_ListOutboundsRequest, Xray_App_Proxyman_Command_ListOutboundsResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Xray_App_Proxyman_Command_HandlerServiceAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Xray_App_Proxyman_Command_HandlerServiceClientMetadata.serviceDescriptor
  }

  public var interceptors: Xray_App_Proxyman_Command_HandlerServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeAddInboundCall(
    _ request: Xray_App_Proxyman_Command_AddInboundRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Xray_App_Proxyman_Command_AddInboundRequest, Xray_App_Proxyman_Command_AddInboundResponse> {
    return self.makeAsyncUnaryCall(
      path: Xray_App_Proxyman_Command_HandlerServiceClientMetadata.Methods.addInbound.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAddInboundInterceptors() ?? []
    )
  }

  public func makeRemoveInboundCall(
    _ request: Xray_App_Proxyman_Command_RemoveInboundRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Xray_App_Proxyman_Command_RemoveInboundRequest, Xray_App_Proxyman_Command_RemoveInboundResponse> {
    return self.makeAsyncUnaryCall(
      path: Xray_App_Proxyman_Command_HandlerServiceClientMetadata.Methods.removeInbound.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRemoveInboundInterceptors() ?? []
    )
  }

  public func makeAlterInboundCall(
    _ request: Xray_App_Proxyman_Command_AlterInboundRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Xray_App_Proxyman_Command_AlterInboundRequest, Xray_App_Proxyman_Command_AlterInboundResponse> {
    return self.makeAsyncUnaryCall(
      path: Xray_App_Proxyman_Command_HandlerServiceClientMetadata.Methods.alterInbound.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAlterInboundInterceptors() ?? []
    )
  }

  public func makeListInboundsCall(
    _ request: Xray_App_Proxyman_Command_ListInboundsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Xray_App_Proxyman_Command_ListInboundsRequest, Xray_App_Proxyman_Command_ListInboundsResponse> {
    return self.makeAsyncUnaryCall(
      path: Xray_App_Proxyman_Command_HandlerServiceClientMetadata.Methods.listInbounds.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListInboundsInterceptors() ?? []
    )
  }

  public func makeGetInboundUsersCall(
    _ request: Xray_App_Proxyman_Command_GetInboundUserRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Xray_App_Proxyman_Command_GetInboundUserRequest, Xray_App_Proxyman_Command_GetInboundUserResponse> {
    return self.makeAsyncUnaryCall(
      path: Xray_App_Proxyman_Command_HandlerServiceClientMetadata.Methods.getInboundUsers.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetInboundUsersInterceptors() ?? []
    )
  }

  public func makeGetInboundUsersCountCall(
    _ request: Xray_App_Proxyman_Command_GetInboundUserRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Xray_App_Proxyman_Command_GetInboundUserRequest, Xray_App_Proxyman_Command_GetInboundUsersCountResponse> {
    return self.makeAsyncUnaryCall(
      path: Xray_App_Proxyman_Command_HandlerServiceClientMetadata.Methods.getInboundUsersCount.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetInboundUsersCountInterceptors() ?? []
    )
  }

  public func makeAddOutboundCall(
    _ request: Xray_App_Proxyman_Command_AddOutboundRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Xray_App_Proxyman_Command_AddOutboundRequest, Xray_App_Proxyman_Command_AddOutboundResponse> {
    return self.makeAsyncUnaryCall(
      path: Xray_App_Proxyman_Command_HandlerServiceClientMetadata.Methods.addOutbound.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAddOutboundInterceptors() ?? []
    )
  }

  public func makeRemoveOutboundCall(
    _ request: Xray_App_Proxyman_Command_RemoveOutboundRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Xray_App_Proxyman_Command_RemoveOutboundRequest, Xray_App_Proxyman_Command_RemoveOutboundResponse> {
    return self.makeAsyncUnaryCall(
      path: Xray_App_Proxyman_Command_HandlerServiceClientMetadata.Methods.removeOutbound.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRemoveOutboundInterceptors() ?? []
    )
  }

  public func makeAlterOutboundCall(
    _ request: Xray_App_Proxyman_Command_AlterOutboundRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Xray_App_Proxyman_Command_AlterOutboundRequest, Xray_App_Proxyman_Command_AlterOutboundResponse> {
    return self.makeAsyncUnaryCall(
      path: Xray_App_Proxyman_Command_HandlerServiceClientMetadata.Methods.alterOutbound.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAlterOutboundInterceptors() ?? []
    )
  }

  public func makeListOutboundsCall(
    _ request: Xray_App_Proxyman_Command_ListOutboundsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Xray_App_Proxyman_Command_ListOutboundsRequest, Xray_App_Proxyman_Command_ListOutboundsResponse> {
    return self.makeAsyncUnaryCall(
      path: Xray_App_Proxyman_Command_HandlerServiceClientMetadata.Methods.listOutbounds.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListOutboundsInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Xray_App_Proxyman_Command_HandlerServiceAsyncClientProtocol {
  public func addInbound(
    _ request: Xray_App_Proxyman_Command_AddInboundRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Xray_App_Proxyman_Command_AddInboundResponse {
    return try await self.performAsyncUnaryCall(
      path: Xray_App_Proxyman_Command_HandlerServiceClientMetadata.Methods.addInbound.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAddInboundInterceptors() ?? []
    )
  }

  public func removeInbound(
    _ request: Xray_App_Proxyman_Command_RemoveInboundRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Xray_App_Proxyman_Command_RemoveInboundResponse {
    return try await self.performAsyncUnaryCall(
      path: Xray_App_Proxyman_Command_HandlerServiceClientMetadata.Methods.removeInbound.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRemoveInboundInterceptors() ?? []
    )
  }

  public func alterInbound(
    _ request: Xray_App_Proxyman_Command_AlterInboundRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Xray_App_Proxyman_Command_AlterInboundResponse {
    return try await self.performAsyncUnaryCall(
      path: Xray_App_Proxyman_Command_HandlerServiceClientMetadata.Methods.alterInbound.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAlterInboundInterceptors() ?? []
    )
  }

  public func listInbounds(
    _ request: Xray_App_Proxyman_Command_ListInboundsRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Xray_App_Proxyman_Command_ListInboundsResponse {
    return try await self.performAsyncUnaryCall(
      path: Xray_App_Proxyman_Command_HandlerServiceClientMetadata.Methods.listInbounds.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListInboundsInterceptors() ?? []
    )
  }

  public func getInboundUsers(
    _ request: Xray_App_Proxyman_Command_GetInboundUserRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Xray_App_Proxyman_Command_GetInboundUserResponse {
    return try await self.performAsyncUnaryCall(
      path: Xray_App_Proxyman_Command_HandlerServiceClientMetadata.Methods.getInboundUsers.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetInboundUsersInterceptors() ?? []
    )
  }

  public func getInboundUsersCount(
    _ request: Xray_App_Proxyman_Command_GetInboundUserRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Xray_App_Proxyman_Command_GetInboundUsersCountResponse {
    return try await self.performAsyncUnaryCall(
      path: Xray_App_Proxyman_Command_HandlerServiceClientMetadata.Methods.getInboundUsersCount.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetInboundUsersCountInterceptors() ?? []
    )
  }

  public func addOutbound(
    _ request: Xray_App_Proxyman_Command_AddOutboundRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Xray_App_Proxyman_Command_AddOutboundResponse {
    return try await self.performAsyncUnaryCall(
      path: Xray_App_Proxyman_Command_HandlerServiceClientMetadata.Methods.addOutbound.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAddOutboundInterceptors() ?? []
    )
  }

  public func removeOutbound(
    _ request: Xray_App_Proxyman_Command_RemoveOutboundRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Xray_App_Proxyman_Command_RemoveOutboundResponse {
    return try await self.performAsyncUnaryCall(
      path: Xray_App_Proxyman_Command_HandlerServiceClientMetadata.Methods.removeOutbound.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRemoveOutboundInterceptors() ?? []
    )
  }

  public func alterOutbound(
    _ request: Xray_App_Proxyman_Command_AlterOutboundRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Xray_App_Proxyman_Command_AlterOutboundResponse {
    return try await self.performAsyncUnaryCall(
      path: Xray_App_Proxyman_Command_HandlerServiceClientMetadata.Methods.alterOutbound.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAlterOutboundInterceptors() ?? []
    )
  }

  public func listOutbounds(
    _ request: Xray_App_Proxyman_Command_ListOutboundsRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Xray_App_Proxyman_Command_ListOutboundsResponse {
    return try await self.performAsyncUnaryCall(
      path: Xray_App_Proxyman_Command_HandlerServiceClientMetadata.Methods.listOutbounds.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListOutboundsInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Xray_App_Proxyman_Command_HandlerServiceAsyncClient: Xray_App_Proxyman_Command_HandlerServiceAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Xray_App_Proxyman_Command_HandlerServiceClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Xray_App_Proxyman_Command_HandlerServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

public protocol Xray_App_Proxyman_Command_HandlerServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'addInbound'.
  func makeAddInboundInterceptors() -> [ClientInterceptor<Xray_App_Proxyman_Command_AddInboundRequest, Xray_App_Proxyman_Command_AddInboundResponse>]

  /// - Returns: Interceptors to use when invoking 'removeInbound'.
  func makeRemoveInboundInterceptors() -> [ClientInterceptor<Xray_App_Proxyman_Command_RemoveInboundRequest, Xray_App_Proxyman_Command_RemoveInboundResponse>]

  /// - Returns: Interceptors to use when invoking 'alterInbound'.
  func makeAlterInboundInterceptors() -> [ClientInterceptor<Xray_App_Proxyman_Command_AlterInboundRequest, Xray_App_Proxyman_Command_AlterInboundResponse>]

  /// - Returns: Interceptors to use when invoking 'listInbounds'.
  func makeListInboundsInterceptors() -> [ClientInterceptor<Xray_App_Proxyman_Command_ListInboundsRequest, Xray_App_Proxyman_Command_ListInboundsResponse>]

  /// - Returns: Interceptors to use when invoking 'getInboundUsers'.
  func makeGetInboundUsersInterceptors() -> [ClientInterceptor<Xray_App_Proxyman_Command_GetInboundUserRequest, Xray_App_Proxyman_Command_GetInboundUserResponse>]

  /// - Returns: Interceptors to use when invoking 'getInboundUsersCount'.
  func makeGetInboundUsersCountInterceptors() -> [ClientInterceptor<Xray_App_Proxyman_Command_GetInboundUserRequest, Xray_App_Proxyman_Command_GetInboundUsersCountResponse>]

  /// - Returns: Interceptors to use when invoking 'addOutbound'.
  func makeAddOutboundInterceptors() -> [ClientInterceptor<Xray_App_Proxyman_Command_AddOutboundRequest, Xray_App_Proxyman_Command_AddOutboundResponse>]

  /// - Returns: Interceptors to use when invoking 'removeOutbound'.
  func makeRemoveOutboundInterceptors() -> [ClientInterceptor<Xray_App_Proxyman_Command_RemoveOutboundRequest, Xray_App_Proxyman_Command_RemoveOutboundResponse>]

  /// - Returns: Interceptors to use when invoking 'alterOutbound'.
  func makeAlterOutboundInterceptors() -> [ClientInterceptor<Xray_App_Proxyman_Command_AlterOutboundRequest, Xray_App_Proxyman_Command_AlterOutboundResponse>]

  /// - Returns: Interceptors to use when invoking 'listOutbounds'.
  func makeListOutboundsInterceptors() -> [ClientInterceptor<Xray_App_Proxyman_Command_ListOutboundsRequest, Xray_App_Proxyman_Command_ListOutboundsResponse>]
}

public enum Xray_App_Proxyman_Command_HandlerServiceClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "HandlerService",
    fullName: "xray.app.proxyman.command.HandlerService",
    methods: [
      Xray_App_Proxyman_Command_HandlerServiceClientMetadata.Methods.addInbound,
      Xray_App_Proxyman_Command_HandlerServiceClientMetadata.Methods.removeInbound,
      Xray_App_Proxyman_Command_HandlerServiceClientMetadata.Methods.alterInbound,
      Xray_App_Proxyman_Command_HandlerServiceClientMetadata.Methods.listInbounds,
      Xray_App_Proxyman_Command_HandlerServiceClientMetadata.Methods.getInboundUsers,
      Xray_App_Proxyman_Command_HandlerServiceClientMetadata.Methods.getInboundUsersCount,
      Xray_App_Proxyman_Command_HandlerServiceClientMetadata.Methods.addOutbound,
      Xray_App_Proxyman_Command_HandlerServiceClientMetadata.Methods.removeOutbound,
      Xray_App_Proxyman_Command_HandlerServiceClientMetadata.Methods.alterOutbound,
      Xray_App_Proxyman_Command_HandlerServiceClientMetadata.Methods.listOutbounds,
    ]
  )

  public enum Methods {
    public static let addInbound = GRPCMethodDescriptor(
      name: "AddInbound",
      path: "/xray.app.proxyman.command.HandlerService/AddInbound",
      type: GRPCCallType.unary
    )

    public static let removeInbound = GRPCMethodDescriptor(
      name: "RemoveInbound",
      path: "/xray.app.proxyman.command.HandlerService/RemoveInbound",
      type: GRPCCallType.unary
    )

    public static let alterInbound = GRPCMethodDescriptor(
      name: "AlterInbound",
      path: "/xray.app.proxyman.command.HandlerService/AlterInbound",
      type: GRPCCallType.unary
    )

    public static let listInbounds = GRPCMethodDescriptor(
      name: "ListInbounds",
      path: "/xray.app.proxyman.command.HandlerService/ListInbounds",
      type: GRPCCallType.unary
    )

    public static let getInboundUsers = GRPCMethodDescriptor(
      name: "GetInboundUsers",
      path: "/xray.app.proxyman.command.HandlerService/GetInboundUsers",
      type: GRPCCallType.unary
    )

    public static let getInboundUsersCount = GRPCMethodDescriptor(
      name: "GetInboundUsersCount",
      path: "/xray.app.proxyman.command.HandlerService/GetInboundUsersCount",
      type: GRPCCallType.unary
    )

    public static let addOutbound = GRPCMethodDescriptor(
      name: "AddOutbound",
      path: "/xray.app.proxyman.command.HandlerService/AddOutbound",
      type: GRPCCallType.unary
    )

    public static let removeOutbound = GRPCMethodDescriptor(
      name: "RemoveOutbound",
      path: "/xray.app.proxyman.command.HandlerService/RemoveOutbound",
      type: GRPCCallType.unary
    )

    public static let alterOutbound = GRPCMethodDescriptor(
      name: "AlterOutbound",
      path: "/xray.app.proxyman.command.HandlerService/AlterOutbound",
      type: GRPCCallType.unary
    )

    public static let listOutbounds = GRPCMethodDescriptor(
      name: "ListOutbounds",
      path: "/xray.app.proxyman.command.HandlerService/ListOutbounds",
      type: GRPCCallType.unary
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
public protocol Xray_App_Proxyman_Command_HandlerServiceProvider: CallHandlerProvider {
  var interceptors: Xray_App_Proxyman_Command_HandlerServiceServerInterceptorFactoryProtocol? { get }

  func addInbound(request: Xray_App_Proxyman_Command_AddInboundRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Xray_App_Proxyman_Command_AddInboundResponse>

  func removeInbound(request: Xray_App_Proxyman_Command_RemoveInboundRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Xray_App_Proxyman_Command_RemoveInboundResponse>

  func alterInbound(request: Xray_App_Proxyman_Command_AlterInboundRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Xray_App_Proxyman_Command_AlterInboundResponse>

  func listInbounds(request: Xray_App_Proxyman_Command_ListInboundsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Xray_App_Proxyman_Command_ListInboundsResponse>

  func getInboundUsers(request: Xray_App_Proxyman_Command_GetInboundUserRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Xray_App_Proxyman_Command_GetInboundUserResponse>

  func getInboundUsersCount(request: Xray_App_Proxyman_Command_GetInboundUserRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Xray_App_Proxyman_Command_GetInboundUsersCountResponse>

  func addOutbound(request: Xray_App_Proxyman_Command_AddOutboundRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Xray_App_Proxyman_Command_AddOutboundResponse>

  func removeOutbound(request: Xray_App_Proxyman_Command_RemoveOutboundRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Xray_App_Proxyman_Command_RemoveOutboundResponse>

  func alterOutbound(request: Xray_App_Proxyman_Command_AlterOutboundRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Xray_App_Proxyman_Command_AlterOutboundResponse>

  func listOutbounds(request: Xray_App_Proxyman_Command_ListOutboundsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Xray_App_Proxyman_Command_ListOutboundsResponse>
}

extension Xray_App_Proxyman_Command_HandlerServiceProvider {
  public var serviceName: Substring {
    return Xray_App_Proxyman_Command_HandlerServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "AddInbound":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Xray_App_Proxyman_Command_AddInboundRequest>(),
        responseSerializer: ProtobufSerializer<Xray_App_Proxyman_Command_AddInboundResponse>(),
        interceptors: self.interceptors?.makeAddInboundInterceptors() ?? [],
        userFunction: self.addInbound(request:context:)
      )

    case "RemoveInbound":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Xray_App_Proxyman_Command_RemoveInboundRequest>(),
        responseSerializer: ProtobufSerializer<Xray_App_Proxyman_Command_RemoveInboundResponse>(),
        interceptors: self.interceptors?.makeRemoveInboundInterceptors() ?? [],
        userFunction: self.removeInbound(request:context:)
      )

    case "AlterInbound":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Xray_App_Proxyman_Command_AlterInboundRequest>(),
        responseSerializer: ProtobufSerializer<Xray_App_Proxyman_Command_AlterInboundResponse>(),
        interceptors: self.interceptors?.makeAlterInboundInterceptors() ?? [],
        userFunction: self.alterInbound(request:context:)
      )

    case "ListInbounds":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Xray_App_Proxyman_Command_ListInboundsRequest>(),
        responseSerializer: ProtobufSerializer<Xray_App_Proxyman_Command_ListInboundsResponse>(),
        interceptors: self.interceptors?.makeListInboundsInterceptors() ?? [],
        userFunction: self.listInbounds(request:context:)
      )

    case "GetInboundUsers":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Xray_App_Proxyman_Command_GetInboundUserRequest>(),
        responseSerializer: ProtobufSerializer<Xray_App_Proxyman_Command_GetInboundUserResponse>(),
        interceptors: self.interceptors?.makeGetInboundUsersInterceptors() ?? [],
        userFunction: self.getInboundUsers(request:context:)
      )

    case "GetInboundUsersCount":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Xray_App_Proxyman_Command_GetInboundUserRequest>(),
        responseSerializer: ProtobufSerializer<Xray_App_Proxyman_Command_GetInboundUsersCountResponse>(),
        interceptors: self.interceptors?.makeGetInboundUsersCountInterceptors() ?? [],
        userFunction: self.getInboundUsersCount(request:context:)
      )

    case "AddOutbound":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Xray_App_Proxyman_Command_AddOutboundRequest>(),
        responseSerializer: ProtobufSerializer<Xray_App_Proxyman_Command_AddOutboundResponse>(),
        interceptors: self.interceptors?.makeAddOutboundInterceptors() ?? [],
        userFunction: self.addOutbound(request:context:)
      )

    case "RemoveOutbound":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Xray_App_Proxyman_Command_RemoveOutboundRequest>(),
        responseSerializer: ProtobufSerializer<Xray_App_Proxyman_Command_RemoveOutboundResponse>(),
        interceptors: self.interceptors?.makeRemoveOutboundInterceptors() ?? [],
        userFunction: self.removeOutbound(request:context:)
      )

    case "AlterOutbound":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Xray_App_Proxyman_Command_AlterOutboundRequest>(),
        responseSerializer: ProtobufSerializer<Xray_App_Proxyman_Command_AlterOutboundResponse>(),
        interceptors: self.interceptors?.makeAlterOutboundInterceptors() ?? [],
        userFunction: self.alterOutbound(request:context:)
      )

    case "ListOutbounds":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Xray_App_Proxyman_Command_ListOutboundsRequest>(),
        responseSerializer: ProtobufSerializer<Xray_App_Proxyman_Command_ListOutboundsResponse>(),
        interceptors: self.interceptors?.makeListOutboundsInterceptors() ?? [],
        userFunction: self.listOutbounds(request:context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Xray_App_Proxyman_Command_HandlerServiceAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Xray_App_Proxyman_Command_HandlerServiceServerInterceptorFactoryProtocol? { get }

  func addInbound(
    request: Xray_App_Proxyman_Command_AddInboundRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Xray_App_Proxyman_Command_AddInboundResponse

  func removeInbound(
    request: Xray_App_Proxyman_Command_RemoveInboundRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Xray_App_Proxyman_Command_RemoveInboundResponse

  func alterInbound(
    request: Xray_App_Proxyman_Command_AlterInboundRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Xray_App_Proxyman_Command_AlterInboundResponse

  func listInbounds(
    request: Xray_App_Proxyman_Command_ListInboundsRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Xray_App_Proxyman_Command_ListInboundsResponse

  func getInboundUsers(
    request: Xray_App_Proxyman_Command_GetInboundUserRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Xray_App_Proxyman_Command_GetInboundUserResponse

  func getInboundUsersCount(
    request: Xray_App_Proxyman_Command_GetInboundUserRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Xray_App_Proxyman_Command_GetInboundUsersCountResponse

  func addOutbound(
    request: Xray_App_Proxyman_Command_AddOutboundRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Xray_App_Proxyman_Command_AddOutboundResponse

  func removeOutbound(
    request: Xray_App_Proxyman_Command_RemoveOutboundRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Xray_App_Proxyman_Command_RemoveOutboundResponse

  func alterOutbound(
    request: Xray_App_Proxyman_Command_AlterOutboundRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Xray_App_Proxyman_Command_AlterOutboundResponse

  func listOutbounds(
    request: Xray_App_Proxyman_Command_ListOutboundsRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Xray_App_Proxyman_Command_ListOutboundsResponse
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Xray_App_Proxyman_Command_HandlerServiceAsyncProvider {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Xray_App_Proxyman_Command_HandlerServiceServerMetadata.serviceDescriptor
  }

  public var serviceName: Substring {
    return Xray_App_Proxyman_Command_HandlerServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  public var interceptors: Xray_App_Proxyman_Command_HandlerServiceServerInterceptorFactoryProtocol? {
    return nil
  }

  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "AddInbound":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Xray_App_Proxyman_Command_AddInboundRequest>(),
        responseSerializer: ProtobufSerializer<Xray_App_Proxyman_Command_AddInboundResponse>(),
        interceptors: self.interceptors?.makeAddInboundInterceptors() ?? [],
        wrapping: { try await self.addInbound(request: $0, context: $1) }
      )

    case "RemoveInbound":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Xray_App_Proxyman_Command_RemoveInboundRequest>(),
        responseSerializer: ProtobufSerializer<Xray_App_Proxyman_Command_RemoveInboundResponse>(),
        interceptors: self.interceptors?.makeRemoveInboundInterceptors() ?? [],
        wrapping: { try await self.removeInbound(request: $0, context: $1) }
      )

    case "AlterInbound":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Xray_App_Proxyman_Command_AlterInboundRequest>(),
        responseSerializer: ProtobufSerializer<Xray_App_Proxyman_Command_AlterInboundResponse>(),
        interceptors: self.interceptors?.makeAlterInboundInterceptors() ?? [],
        wrapping: { try await self.alterInbound(request: $0, context: $1) }
      )

    case "ListInbounds":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Xray_App_Proxyman_Command_ListInboundsRequest>(),
        responseSerializer: ProtobufSerializer<Xray_App_Proxyman_Command_ListInboundsResponse>(),
        interceptors: self.interceptors?.makeListInboundsInterceptors() ?? [],
        wrapping: { try await self.listInbounds(request: $0, context: $1) }
      )

    case "GetInboundUsers":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Xray_App_Proxyman_Command_GetInboundUserRequest>(),
        responseSerializer: ProtobufSerializer<Xray_App_Proxyman_Command_GetInboundUserResponse>(),
        interceptors: self.interceptors?.makeGetInboundUsersInterceptors() ?? [],
        wrapping: { try await self.getInboundUsers(request: $0, context: $1) }
      )

    case "GetInboundUsersCount":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Xray_App_Proxyman_Command_GetInboundUserRequest>(),
        responseSerializer: ProtobufSerializer<Xray_App_Proxyman_Command_GetInboundUsersCountResponse>(),
        interceptors: self.interceptors?.makeGetInboundUsersCountInterceptors() ?? [],
        wrapping: { try await self.getInboundUsersCount(request: $0, context: $1) }
      )

    case "AddOutbound":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Xray_App_Proxyman_Command_AddOutboundRequest>(),
        responseSerializer: ProtobufSerializer<Xray_App_Proxyman_Command_AddOutboundResponse>(),
        interceptors: self.interceptors?.makeAddOutboundInterceptors() ?? [],
        wrapping: { try await self.addOutbound(request: $0, context: $1) }
      )

    case "RemoveOutbound":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Xray_App_Proxyman_Command_RemoveOutboundRequest>(),
        responseSerializer: ProtobufSerializer<Xray_App_Proxyman_Command_RemoveOutboundResponse>(),
        interceptors: self.interceptors?.makeRemoveOutboundInterceptors() ?? [],
        wrapping: { try await self.removeOutbound(request: $0, context: $1) }
      )

    case "AlterOutbound":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Xray_App_Proxyman_Command_AlterOutboundRequest>(),
        responseSerializer: ProtobufSerializer<Xray_App_Proxyman_Command_AlterOutboundResponse>(),
        interceptors: self.interceptors?.makeAlterOutboundInterceptors() ?? [],
        wrapping: { try await self.alterOutbound(request: $0, context: $1) }
      )

    case "ListOutbounds":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Xray_App_Proxyman_Command_ListOutboundsRequest>(),
        responseSerializer: ProtobufSerializer<Xray_App_Proxyman_Command_ListOutboundsResponse>(),
        interceptors: self.interceptors?.makeListOutboundsInterceptors() ?? [],
        wrapping: { try await self.listOutbounds(request: $0, context: $1) }
      )

    default:
      return nil
    }
  }
}

public protocol Xray_App_Proxyman_Command_HandlerServiceServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'addInbound'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeAddInboundInterceptors() -> [ServerInterceptor<Xray_App_Proxyman_Command_AddInboundRequest, Xray_App_Proxyman_Command_AddInboundResponse>]

  /// - Returns: Interceptors to use when handling 'removeInbound'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeRemoveInboundInterceptors() -> [ServerInterceptor<Xray_App_Proxyman_Command_RemoveInboundRequest, Xray_App_Proxyman_Command_RemoveInboundResponse>]

  /// - Returns: Interceptors to use when handling 'alterInbound'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeAlterInboundInterceptors() -> [ServerInterceptor<Xray_App_Proxyman_Command_AlterInboundRequest, Xray_App_Proxyman_Command_AlterInboundResponse>]

  /// - Returns: Interceptors to use when handling 'listInbounds'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeListInboundsInterceptors() -> [ServerInterceptor<Xray_App_Proxyman_Command_ListInboundsRequest, Xray_App_Proxyman_Command_ListInboundsResponse>]

  /// - Returns: Interceptors to use when handling 'getInboundUsers'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetInboundUsersInterceptors() -> [ServerInterceptor<Xray_App_Proxyman_Command_GetInboundUserRequest, Xray_App_Proxyman_Command_GetInboundUserResponse>]

  /// - Returns: Interceptors to use when handling 'getInboundUsersCount'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetInboundUsersCountInterceptors() -> [ServerInterceptor<Xray_App_Proxyman_Command_GetInboundUserRequest, Xray_App_Proxyman_Command_GetInboundUsersCountResponse>]

  /// - Returns: Interceptors to use when handling 'addOutbound'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeAddOutboundInterceptors() -> [ServerInterceptor<Xray_App_Proxyman_Command_AddOutboundRequest, Xray_App_Proxyman_Command_AddOutboundResponse>]

  /// - Returns: Interceptors to use when handling 'removeOutbound'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeRemoveOutboundInterceptors() -> [ServerInterceptor<Xray_App_Proxyman_Command_RemoveOutboundRequest, Xray_App_Proxyman_Command_RemoveOutboundResponse>]

  /// - Returns: Interceptors to use when handling 'alterOutbound'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeAlterOutboundInterceptors() -> [ServerInterceptor<Xray_App_Proxyman_Command_AlterOutboundRequest, Xray_App_Proxyman_Command_AlterOutboundResponse>]

  /// - Returns: Interceptors to use when handling 'listOutbounds'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeListOutboundsInterceptors() -> [ServerInterceptor<Xray_App_Proxyman_Command_ListOutboundsRequest, Xray_App_Proxyman_Command_ListOutboundsResponse>]
}

public enum Xray_App_Proxyman_Command_HandlerServiceServerMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "HandlerService",
    fullName: "xray.app.proxyman.command.HandlerService",
    methods: [
      Xray_App_Proxyman_Command_HandlerServiceServerMetadata.Methods.addInbound,
      Xray_App_Proxyman_Command_HandlerServiceServerMetadata.Methods.removeInbound,
      Xray_App_Proxyman_Command_HandlerServiceServerMetadata.Methods.alterInbound,
      Xray_App_Proxyman_Command_HandlerServiceServerMetadata.Methods.listInbounds,
      Xray_App_Proxyman_Command_HandlerServiceServerMetadata.Methods.getInboundUsers,
      Xray_App_Proxyman_Command_HandlerServiceServerMetadata.Methods.getInboundUsersCount,
      Xray_App_Proxyman_Command_HandlerServiceServerMetadata.Methods.addOutbound,
      Xray_App_Proxyman_Command_HandlerServiceServerMetadata.Methods.removeOutbound,
      Xray_App_Proxyman_Command_HandlerServiceServerMetadata.Methods.alterOutbound,
      Xray_App_Proxyman_Command_HandlerServiceServerMetadata.Methods.listOutbounds,
    ]
  )

  public enum Methods {
    public static let addInbound = GRPCMethodDescriptor(
      name: "AddInbound",
      path: "/xray.app.proxyman.command.HandlerService/AddInbound",
      type: GRPCCallType.unary
    )

    public static let removeInbound = GRPCMethodDescriptor(
      name: "RemoveInbound",
      path: "/xray.app.proxyman.command.HandlerService/RemoveInbound",
      type: GRPCCallType.unary
    )

    public static let alterInbound = GRPCMethodDescriptor(
      name: "AlterInbound",
      path: "/xray.app.proxyman.command.HandlerService/AlterInbound",
      type: GRPCCallType.unary
    )

    public static let listInbounds = GRPCMethodDescriptor(
      name: "ListInbounds",
      path: "/xray.app.proxyman.command.HandlerService/ListInbounds",
      type: GRPCCallType.unary
    )

    public static let getInboundUsers = GRPCMethodDescriptor(
      name: "GetInboundUsers",
      path: "/xray.app.proxyman.command.HandlerService/GetInboundUsers",
      type: GRPCCallType.unary
    )

    public static let getInboundUsersCount = GRPCMethodDescriptor(
      name: "GetInboundUsersCount",
      path: "/xray.app.proxyman.command.HandlerService/GetInboundUsersCount",
      type: GRPCCallType.unary
    )

    public static let addOutbound = GRPCMethodDescriptor(
      name: "AddOutbound",
      path: "/xray.app.proxyman.command.HandlerService/AddOutbound",
      type: GRPCCallType.unary
    )

    public static let removeOutbound = GRPCMethodDescriptor(
      name: "RemoveOutbound",
      path: "/xray.app.proxyman.command.HandlerService/RemoveOutbound",
      type: GRPCCallType.unary
    )

    public static let alterOutbound = GRPCMethodDescriptor(
      name: "AlterOutbound",
      path: "/xray.app.proxyman.command.HandlerService/AlterOutbound",
      type: GRPCCallType.unary
    )

    public static let listOutbounds = GRPCMethodDescriptor(
      name: "ListOutbounds",
      path: "/xray.app.proxyman.command.HandlerService/ListOutbounds",
      type: GRPCCallType.unary
    )
  }
}
