//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: transport/internet/grpc/encoding/stream.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Xray_Transport_Internet_Grpc_Encoding_GRPCServiceClient`, then call methods of this protocol to make API calls.
public protocol Xray_Transport_Internet_Grpc_Encoding_GRPCServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Xray_Transport_Internet_Grpc_Encoding_GRPCServiceClientInterceptorFactoryProtocol? { get }

  func tun(
    callOptions: CallOptions?,
    handler: @escaping (Xray_Transport_Internet_Grpc_Encoding_Hunk) -> Void
  ) -> BidirectionalStreamingCall<Xray_Transport_Internet_Grpc_Encoding_Hunk, Xray_Transport_Internet_Grpc_Encoding_Hunk>

  func tunMulti(
    callOptions: CallOptions?,
    handler: @escaping (Xray_Transport_Internet_Grpc_Encoding_MultiHunk) -> Void
  ) -> BidirectionalStreamingCall<Xray_Transport_Internet_Grpc_Encoding_MultiHunk, Xray_Transport_Internet_Grpc_Encoding_MultiHunk>
}

extension Xray_Transport_Internet_Grpc_Encoding_GRPCServiceClientProtocol {
  public var serviceName: String {
    return "xray.transport.internet.grpc.encoding.GRPCService"
  }

  /// Bidirectional streaming call to Tun
  ///
  /// Callers should use the `send` method on the returned object to send messages
  /// to the server. The caller should send an `.end` after the final message has been sent.
  ///
  /// - Parameters:
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ClientStreamingCall` with futures for the metadata and status.
  public func tun(
    callOptions: CallOptions? = nil,
    handler: @escaping (Xray_Transport_Internet_Grpc_Encoding_Hunk) -> Void
  ) -> BidirectionalStreamingCall<Xray_Transport_Internet_Grpc_Encoding_Hunk, Xray_Transport_Internet_Grpc_Encoding_Hunk> {
    return self.makeBidirectionalStreamingCall(
      path: Xray_Transport_Internet_Grpc_Encoding_GRPCServiceClientMetadata.Methods.tun.path,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeTunInterceptors() ?? [],
      handler: handler
    )
  }

  /// Bidirectional streaming call to TunMulti
  ///
  /// Callers should use the `send` method on the returned object to send messages
  /// to the server. The caller should send an `.end` after the final message has been sent.
  ///
  /// - Parameters:
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ClientStreamingCall` with futures for the metadata and status.
  public func tunMulti(
    callOptions: CallOptions? = nil,
    handler: @escaping (Xray_Transport_Internet_Grpc_Encoding_MultiHunk) -> Void
  ) -> BidirectionalStreamingCall<Xray_Transport_Internet_Grpc_Encoding_MultiHunk, Xray_Transport_Internet_Grpc_Encoding_MultiHunk> {
    return self.makeBidirectionalStreamingCall(
      path: Xray_Transport_Internet_Grpc_Encoding_GRPCServiceClientMetadata.Methods.tunMulti.path,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeTunMultiInterceptors() ?? [],
      handler: handler
    )
  }
}

@available(*, deprecated)
extension Xray_Transport_Internet_Grpc_Encoding_GRPCServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Xray_Transport_Internet_Grpc_Encoding_GRPCServiceNIOClient")
public final class Xray_Transport_Internet_Grpc_Encoding_GRPCServiceClient: Xray_Transport_Internet_Grpc_Encoding_GRPCServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Xray_Transport_Internet_Grpc_Encoding_GRPCServiceClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: Xray_Transport_Internet_Grpc_Encoding_GRPCServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the xray.transport.internet.grpc.encoding.GRPCService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Xray_Transport_Internet_Grpc_Encoding_GRPCServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct Xray_Transport_Internet_Grpc_Encoding_GRPCServiceNIOClient: Xray_Transport_Internet_Grpc_Encoding_GRPCServiceClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Xray_Transport_Internet_Grpc_Encoding_GRPCServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the xray.transport.internet.grpc.encoding.GRPCService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Xray_Transport_Internet_Grpc_Encoding_GRPCServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Xray_Transport_Internet_Grpc_Encoding_GRPCServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Xray_Transport_Internet_Grpc_Encoding_GRPCServiceClientInterceptorFactoryProtocol? { get }

  func makeTunCall(
    callOptions: CallOptions?
  ) -> GRPCAsyncBidirectionalStreamingCall<Xray_Transport_Internet_Grpc_Encoding_Hunk, Xray_Transport_Internet_Grpc_Encoding_Hunk>

  func makeTunMultiCall(
    callOptions: CallOptions?
  ) -> GRPCAsyncBidirectionalStreamingCall<Xray_Transport_Internet_Grpc_Encoding_MultiHunk, Xray_Transport_Internet_Grpc_Encoding_MultiHunk>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Xray_Transport_Internet_Grpc_Encoding_GRPCServiceAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Xray_Transport_Internet_Grpc_Encoding_GRPCServiceClientMetadata.serviceDescriptor
  }

  public var interceptors: Xray_Transport_Internet_Grpc_Encoding_GRPCServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeTunCall(
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncBidirectionalStreamingCall<Xray_Transport_Internet_Grpc_Encoding_Hunk, Xray_Transport_Internet_Grpc_Encoding_Hunk> {
    return self.makeAsyncBidirectionalStreamingCall(
      path: Xray_Transport_Internet_Grpc_Encoding_GRPCServiceClientMetadata.Methods.tun.path,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeTunInterceptors() ?? []
    )
  }

  public func makeTunMultiCall(
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncBidirectionalStreamingCall<Xray_Transport_Internet_Grpc_Encoding_MultiHunk, Xray_Transport_Internet_Grpc_Encoding_MultiHunk> {
    return self.makeAsyncBidirectionalStreamingCall(
      path: Xray_Transport_Internet_Grpc_Encoding_GRPCServiceClientMetadata.Methods.tunMulti.path,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeTunMultiInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Xray_Transport_Internet_Grpc_Encoding_GRPCServiceAsyncClientProtocol {
  public func tun<RequestStream>(
    _ requests: RequestStream,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncResponseStream<Xray_Transport_Internet_Grpc_Encoding_Hunk> where RequestStream: Sequence, RequestStream.Element == Xray_Transport_Internet_Grpc_Encoding_Hunk {
    return self.performAsyncBidirectionalStreamingCall(
      path: Xray_Transport_Internet_Grpc_Encoding_GRPCServiceClientMetadata.Methods.tun.path,
      requests: requests,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeTunInterceptors() ?? []
    )
  }

  public func tun<RequestStream>(
    _ requests: RequestStream,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncResponseStream<Xray_Transport_Internet_Grpc_Encoding_Hunk> where RequestStream: AsyncSequence & Sendable, RequestStream.Element == Xray_Transport_Internet_Grpc_Encoding_Hunk {
    return self.performAsyncBidirectionalStreamingCall(
      path: Xray_Transport_Internet_Grpc_Encoding_GRPCServiceClientMetadata.Methods.tun.path,
      requests: requests,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeTunInterceptors() ?? []
    )
  }

  public func tunMulti<RequestStream>(
    _ requests: RequestStream,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncResponseStream<Xray_Transport_Internet_Grpc_Encoding_MultiHunk> where RequestStream: Sequence, RequestStream.Element == Xray_Transport_Internet_Grpc_Encoding_MultiHunk {
    return self.performAsyncBidirectionalStreamingCall(
      path: Xray_Transport_Internet_Grpc_Encoding_GRPCServiceClientMetadata.Methods.tunMulti.path,
      requests: requests,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeTunMultiInterceptors() ?? []
    )
  }

  public func tunMulti<RequestStream>(
    _ requests: RequestStream,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncResponseStream<Xray_Transport_Internet_Grpc_Encoding_MultiHunk> where RequestStream: AsyncSequence & Sendable, RequestStream.Element == Xray_Transport_Internet_Grpc_Encoding_MultiHunk {
    return self.performAsyncBidirectionalStreamingCall(
      path: Xray_Transport_Internet_Grpc_Encoding_GRPCServiceClientMetadata.Methods.tunMulti.path,
      requests: requests,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeTunMultiInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Xray_Transport_Internet_Grpc_Encoding_GRPCServiceAsyncClient: Xray_Transport_Internet_Grpc_Encoding_GRPCServiceAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Xray_Transport_Internet_Grpc_Encoding_GRPCServiceClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Xray_Transport_Internet_Grpc_Encoding_GRPCServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

public protocol Xray_Transport_Internet_Grpc_Encoding_GRPCServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'tun'.
  func makeTunInterceptors() -> [ClientInterceptor<Xray_Transport_Internet_Grpc_Encoding_Hunk, Xray_Transport_Internet_Grpc_Encoding_Hunk>]

  /// - Returns: Interceptors to use when invoking 'tunMulti'.
  func makeTunMultiInterceptors() -> [ClientInterceptor<Xray_Transport_Internet_Grpc_Encoding_MultiHunk, Xray_Transport_Internet_Grpc_Encoding_MultiHunk>]
}

public enum Xray_Transport_Internet_Grpc_Encoding_GRPCServiceClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "GRPCService",
    fullName: "xray.transport.internet.grpc.encoding.GRPCService",
    methods: [
      Xray_Transport_Internet_Grpc_Encoding_GRPCServiceClientMetadata.Methods.tun,
      Xray_Transport_Internet_Grpc_Encoding_GRPCServiceClientMetadata.Methods.tunMulti,
    ]
  )

  public enum Methods {
    public static let tun = GRPCMethodDescriptor(
      name: "Tun",
      path: "/xray.transport.internet.grpc.encoding.GRPCService/Tun",
      type: GRPCCallType.bidirectionalStreaming
    )

    public static let tunMulti = GRPCMethodDescriptor(
      name: "TunMulti",
      path: "/xray.transport.internet.grpc.encoding.GRPCService/TunMulti",
      type: GRPCCallType.bidirectionalStreaming
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
public protocol Xray_Transport_Internet_Grpc_Encoding_GRPCServiceProvider: CallHandlerProvider {
  var interceptors: Xray_Transport_Internet_Grpc_Encoding_GRPCServiceServerInterceptorFactoryProtocol? { get }

  func tun(context: StreamingResponseCallContext<Xray_Transport_Internet_Grpc_Encoding_Hunk>) -> EventLoopFuture<(StreamEvent<Xray_Transport_Internet_Grpc_Encoding_Hunk>) -> Void>

  func tunMulti(context: StreamingResponseCallContext<Xray_Transport_Internet_Grpc_Encoding_MultiHunk>) -> EventLoopFuture<(StreamEvent<Xray_Transport_Internet_Grpc_Encoding_MultiHunk>) -> Void>
}

extension Xray_Transport_Internet_Grpc_Encoding_GRPCServiceProvider {
  public var serviceName: Substring {
    return Xray_Transport_Internet_Grpc_Encoding_GRPCServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Tun":
      return BidirectionalStreamingServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Xray_Transport_Internet_Grpc_Encoding_Hunk>(),
        responseSerializer: ProtobufSerializer<Xray_Transport_Internet_Grpc_Encoding_Hunk>(),
        interceptors: self.interceptors?.makeTunInterceptors() ?? [],
        observerFactory: self.tun(context:)
      )

    case "TunMulti":
      return BidirectionalStreamingServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Xray_Transport_Internet_Grpc_Encoding_MultiHunk>(),
        responseSerializer: ProtobufSerializer<Xray_Transport_Internet_Grpc_Encoding_MultiHunk>(),
        interceptors: self.interceptors?.makeTunMultiInterceptors() ?? [],
        observerFactory: self.tunMulti(context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Xray_Transport_Internet_Grpc_Encoding_GRPCServiceAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Xray_Transport_Internet_Grpc_Encoding_GRPCServiceServerInterceptorFactoryProtocol? { get }

  func tun(
    requestStream: GRPCAsyncRequestStream<Xray_Transport_Internet_Grpc_Encoding_Hunk>,
    responseStream: GRPCAsyncResponseStreamWriter<Xray_Transport_Internet_Grpc_Encoding_Hunk>,
    context: GRPCAsyncServerCallContext
  ) async throws

  func tunMulti(
    requestStream: GRPCAsyncRequestStream<Xray_Transport_Internet_Grpc_Encoding_MultiHunk>,
    responseStream: GRPCAsyncResponseStreamWriter<Xray_Transport_Internet_Grpc_Encoding_MultiHunk>,
    context: GRPCAsyncServerCallContext
  ) async throws
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Xray_Transport_Internet_Grpc_Encoding_GRPCServiceAsyncProvider {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Xray_Transport_Internet_Grpc_Encoding_GRPCServiceServerMetadata.serviceDescriptor
  }

  public var serviceName: Substring {
    return Xray_Transport_Internet_Grpc_Encoding_GRPCServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  public var interceptors: Xray_Transport_Internet_Grpc_Encoding_GRPCServiceServerInterceptorFactoryProtocol? {
    return nil
  }

  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Tun":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Xray_Transport_Internet_Grpc_Encoding_Hunk>(),
        responseSerializer: ProtobufSerializer<Xray_Transport_Internet_Grpc_Encoding_Hunk>(),
        interceptors: self.interceptors?.makeTunInterceptors() ?? [],
        wrapping: { try await self.tun(requestStream: $0, responseStream: $1, context: $2) }
      )

    case "TunMulti":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Xray_Transport_Internet_Grpc_Encoding_MultiHunk>(),
        responseSerializer: ProtobufSerializer<Xray_Transport_Internet_Grpc_Encoding_MultiHunk>(),
        interceptors: self.interceptors?.makeTunMultiInterceptors() ?? [],
        wrapping: { try await self.tunMulti(requestStream: $0, responseStream: $1, context: $2) }
      )

    default:
      return nil
    }
  }
}

public protocol Xray_Transport_Internet_Grpc_Encoding_GRPCServiceServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'tun'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeTunInterceptors() -> [ServerInterceptor<Xray_Transport_Internet_Grpc_Encoding_Hunk, Xray_Transport_Internet_Grpc_Encoding_Hunk>]

  /// - Returns: Interceptors to use when handling 'tunMulti'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeTunMultiInterceptors() -> [ServerInterceptor<Xray_Transport_Internet_Grpc_Encoding_MultiHunk, Xray_Transport_Internet_Grpc_Encoding_MultiHunk>]
}

public enum Xray_Transport_Internet_Grpc_Encoding_GRPCServiceServerMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "GRPCService",
    fullName: "xray.transport.internet.grpc.encoding.GRPCService",
    methods: [
      Xray_Transport_Internet_Grpc_Encoding_GRPCServiceServerMetadata.Methods.tun,
      Xray_Transport_Internet_Grpc_Encoding_GRPCServiceServerMetadata.Methods.tunMulti,
    ]
  )

  public enum Methods {
    public static let tun = GRPCMethodDescriptor(
      name: "Tun",
      path: "/xray.transport.internet.grpc.encoding.GRPCService/Tun",
      type: GRPCCallType.bidirectionalStreaming
    )

    public static let tunMulti = GRPCMethodDescriptor(
      name: "TunMulti",
      path: "/xray.transport.internet.grpc.encoding.GRPCService/TunMulti",
      type: GRPCCallType.bidirectionalStreaming
    )
  }
}
