// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: app/version/config.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct Xray_App_Version_Config: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var coreVersion: String = String()

  public var minVersion: String = String()

  public var maxVersion: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "xray.app.version"

extension Xray_App_Version_Config: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Config"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "core_version"),
    2: .standard(proto: "min_version"),
    3: .standard(proto: "max_version"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.coreVersion) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.minVersion) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.maxVersion) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.coreVersion.isEmpty {
      try visitor.visitSingularStringField(value: self.coreVersion, fieldNumber: 1)
    }
    if !self.minVersion.isEmpty {
      try visitor.visitSingularStringField(value: self.minVersion, fieldNumber: 2)
    }
    if !self.maxVersion.isEmpty {
      try visitor.visitSingularStringField(value: self.maxVersion, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Xray_App_Version_Config, rhs: Xray_App_Version_Config) -> Bool {
    if lhs.coreVersion != rhs.coreVersion {return false}
    if lhs.minVersion != rhs.minVersion {return false}
    if lhs.maxVersion != rhs.maxVersion {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
