// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: app/router/config.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct Xray_App_Router_RoutingRule: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var targetTag: OneOf_TargetTag? {
    get {return _storage._targetTag}
    set {_uniqueStorage()._targetTag = newValue}
  }

  /// Tag of outbound that this rule is pointing to.
  public var tag: String {
    get {
      if case .tag(let v)? = _storage._targetTag {return v}
      return String()
    }
    set {_uniqueStorage()._targetTag = .tag(newValue)}
  }

  /// Tag of routing balancer.
  public var balancingTag: String {
    get {
      if case .balancingTag(let v)? = _storage._targetTag {return v}
      return String()
    }
    set {_uniqueStorage()._targetTag = .balancingTag(newValue)}
  }

  public var ruleTag: String {
    get {return _storage._ruleTag}
    set {_uniqueStorage()._ruleTag = newValue}
  }

  /// List of domains for target domain matching.
  public var domain: [Xray_Common_Geodata_DomainRule] {
    get {return _storage._domain}
    set {_uniqueStorage()._domain = newValue}
  }

  /// List of IPs for target IP address matching.
  public var ip: [Xray_Common_Geodata_IPRule] {
    get {return _storage._ip}
    set {_uniqueStorage()._ip = newValue}
  }

  /// List of ports for target port matching.
  public var portList: Xray_Common_Net_PortList {
    get {return _storage._portList ?? Xray_Common_Net_PortList()}
    set {_uniqueStorage()._portList = newValue}
  }
  /// Returns true if `portList` has been explicitly set.
  public var hasPortList: Bool {return _storage._portList != nil}
  /// Clears the value of `portList`. Subsequent reads from it will return its default value.
  public mutating func clearPortList() {_uniqueStorage()._portList = nil}

  /// List of networks for matching.
  public var networks: [Xray_Common_Net_Network] {
    get {return _storage._networks}
    set {_uniqueStorage()._networks = newValue}
  }

  /// List of IPs for source IP address matching.
  public var sourceIp: [Xray_Common_Geodata_IPRule] {
    get {return _storage._sourceIp}
    set {_uniqueStorage()._sourceIp = newValue}
  }

  /// List of ports for source port matching.
  public var sourcePortList: Xray_Common_Net_PortList {
    get {return _storage._sourcePortList ?? Xray_Common_Net_PortList()}
    set {_uniqueStorage()._sourcePortList = newValue}
  }
  /// Returns true if `sourcePortList` has been explicitly set.
  public var hasSourcePortList: Bool {return _storage._sourcePortList != nil}
  /// Clears the value of `sourcePortList`. Subsequent reads from it will return its default value.
  public mutating func clearSourcePortList() {_uniqueStorage()._sourcePortList = nil}

  public var userEmail: [String] {
    get {return _storage._userEmail}
    set {_uniqueStorage()._userEmail = newValue}
  }

  public var inboundTag: [String] {
    get {return _storage._inboundTag}
    set {_uniqueStorage()._inboundTag = newValue}
  }

  public var `protocol`: [String] {
    get {return _storage._protocol}
    set {_uniqueStorage()._protocol = newValue}
  }

  public var attributes: Dictionary<String,String> {
    get {return _storage._attributes}
    set {_uniqueStorage()._attributes = newValue}
  }

  /// List of IPs for local IP address matching.
  public var localIp: [Xray_Common_Geodata_IPRule] {
    get {return _storage._localIp}
    set {_uniqueStorage()._localIp = newValue}
  }

  /// List of ports for local port matching.
  public var localPortList: Xray_Common_Net_PortList {
    get {return _storage._localPortList ?? Xray_Common_Net_PortList()}
    set {_uniqueStorage()._localPortList = newValue}
  }
  /// Returns true if `localPortList` has been explicitly set.
  public var hasLocalPortList: Bool {return _storage._localPortList != nil}
  /// Clears the value of `localPortList`. Subsequent reads from it will return its default value.
  public mutating func clearLocalPortList() {_uniqueStorage()._localPortList = nil}

  public var vlessRouteList: Xray_Common_Net_PortList {
    get {return _storage._vlessRouteList ?? Xray_Common_Net_PortList()}
    set {_uniqueStorage()._vlessRouteList = newValue}
  }
  /// Returns true if `vlessRouteList` has been explicitly set.
  public var hasVlessRouteList: Bool {return _storage._vlessRouteList != nil}
  /// Clears the value of `vlessRouteList`. Subsequent reads from it will return its default value.
  public mutating func clearVlessRouteList() {_uniqueStorage()._vlessRouteList = nil}

  public var process: [String] {
    get {return _storage._process}
    set {_uniqueStorage()._process = newValue}
  }

  public var webhook: Xray_App_Router_WebhookConfig {
    get {return _storage._webhook ?? Xray_App_Router_WebhookConfig()}
    set {_uniqueStorage()._webhook = newValue}
  }
  /// Returns true if `webhook` has been explicitly set.
  public var hasWebhook: Bool {return _storage._webhook != nil}
  /// Clears the value of `webhook`. Subsequent reads from it will return its default value.
  public mutating func clearWebhook() {_uniqueStorage()._webhook = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_TargetTag: Equatable, Sendable {
    /// Tag of outbound that this rule is pointing to.
    case tag(String)
    /// Tag of routing balancer.
    case balancingTag(String)

  }

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct Xray_App_Router_WebhookConfig: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var url: String = String()

  public var deduplication: UInt32 = 0

  public var headers: Dictionary<String,String> = [:]

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Xray_App_Router_BalancingRule: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var tag: String = String()

  public var outboundSelector: [String] = []

  public var strategy: String = String()

  public var strategySettings: Xray_Common_Serial_TypedMessage {
    get {return _strategySettings ?? Xray_Common_Serial_TypedMessage()}
    set {_strategySettings = newValue}
  }
  /// Returns true if `strategySettings` has been explicitly set.
  public var hasStrategySettings: Bool {return self._strategySettings != nil}
  /// Clears the value of `strategySettings`. Subsequent reads from it will return its default value.
  public mutating func clearStrategySettings() {self._strategySettings = nil}

  public var fallbackTag: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _strategySettings: Xray_Common_Serial_TypedMessage? = nil
}

public struct Xray_App_Router_StrategyWeight: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var regexp: Bool = false

  public var match: String = String()

  public var value: Float = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Xray_App_Router_StrategyLeastLoadConfig: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// weight settings
  public var costs: [Xray_App_Router_StrategyWeight] = []

  /// RTT baselines for selecting, int64 values of time.Duration
  public var baselines: [Int64] = []

  /// expected nodes count to select
  public var expected: Int32 = 0

  /// max acceptable rtt, filter away high delay nodes. default 0
  public var maxRtt: Int64 = 0

  /// acceptable failure rate
  public var tolerance: Float = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Xray_App_Router_Config: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var domainStrategy: Xray_App_Router_Config.DomainStrategy = .asIs

  public var rule: [Xray_App_Router_RoutingRule] = []

  public var balancingRule: [Xray_App_Router_BalancingRule] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum DomainStrategy: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int

    /// Use domain as is.
    case asIs // = 0

    /// Resolve to IP if the domain doesn't match any rules.
    case ipIfNonMatch // = 2

    /// Resolve to IP if any rule requires IP matching.
    case ipOnDemand // = 3
    case UNRECOGNIZED(Int)

    public init() {
      self = .asIs
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .asIs
      case 2: self = .ipIfNonMatch
      case 3: self = .ipOnDemand
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .asIs: return 0
      case .ipIfNonMatch: return 2
      case .ipOnDemand: return 3
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [Xray_App_Router_Config.DomainStrategy] = [
      .asIs,
      .ipIfNonMatch,
      .ipOnDemand,
    ]

  }

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "xray.app.router"

extension Xray_App_Router_RoutingRule: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RoutingRule"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "tag"),
    12: .standard(proto: "balancing_tag"),
    19: .standard(proto: "rule_tag"),
    2: .same(proto: "domain"),
    10: .same(proto: "ip"),
    14: .standard(proto: "port_list"),
    13: .same(proto: "networks"),
    11: .standard(proto: "source_ip"),
    16: .standard(proto: "source_port_list"),
    7: .standard(proto: "user_email"),
    8: .standard(proto: "inbound_tag"),
    9: .same(proto: "protocol"),
    15: .same(proto: "attributes"),
    17: .standard(proto: "local_ip"),
    18: .standard(proto: "local_port_list"),
    20: .standard(proto: "vless_route_list"),
    21: .same(proto: "process"),
    22: .same(proto: "webhook"),
  ]

  fileprivate class _StorageClass {
    var _targetTag: Xray_App_Router_RoutingRule.OneOf_TargetTag?
    var _ruleTag: String = String()
    var _domain: [Xray_Common_Geodata_DomainRule] = []
    var _ip: [Xray_Common_Geodata_IPRule] = []
    var _portList: Xray_Common_Net_PortList? = nil
    var _networks: [Xray_Common_Net_Network] = []
    var _sourceIp: [Xray_Common_Geodata_IPRule] = []
    var _sourcePortList: Xray_Common_Net_PortList? = nil
    var _userEmail: [String] = []
    var _inboundTag: [String] = []
    var _protocol: [String] = []
    var _attributes: Dictionary<String,String> = [:]
    var _localIp: [Xray_Common_Geodata_IPRule] = []
    var _localPortList: Xray_Common_Net_PortList? = nil
    var _vlessRouteList: Xray_Common_Net_PortList? = nil
    var _process: [String] = []
    var _webhook: Xray_App_Router_WebhookConfig? = nil

    #if swift(>=5.10)
      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()
    #else
      static let defaultInstance = _StorageClass()
    #endif

    private init() {}

    init(copying source: _StorageClass) {
      _targetTag = source._targetTag
      _ruleTag = source._ruleTag
      _domain = source._domain
      _ip = source._ip
      _portList = source._portList
      _networks = source._networks
      _sourceIp = source._sourceIp
      _sourcePortList = source._sourcePortList
      _userEmail = source._userEmail
      _inboundTag = source._inboundTag
      _protocol = source._protocol
      _attributes = source._attributes
      _localIp = source._localIp
      _localPortList = source._localPortList
      _vlessRouteList = source._vlessRouteList
      _process = source._process
      _webhook = source._webhook
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try {
          var v: String?
          try decoder.decodeSingularStringField(value: &v)
          if let v = v {
            if _storage._targetTag != nil {try decoder.handleConflictingOneOf()}
            _storage._targetTag = .tag(v)
          }
        }()
        case 2: try { try decoder.decodeRepeatedMessageField(value: &_storage._domain) }()
        case 7: try { try decoder.decodeRepeatedStringField(value: &_storage._userEmail) }()
        case 8: try { try decoder.decodeRepeatedStringField(value: &_storage._inboundTag) }()
        case 9: try { try decoder.decodeRepeatedStringField(value: &_storage._protocol) }()
        case 10: try { try decoder.decodeRepeatedMessageField(value: &_storage._ip) }()
        case 11: try { try decoder.decodeRepeatedMessageField(value: &_storage._sourceIp) }()
        case 12: try {
          var v: String?
          try decoder.decodeSingularStringField(value: &v)
          if let v = v {
            if _storage._targetTag != nil {try decoder.handleConflictingOneOf()}
            _storage._targetTag = .balancingTag(v)
          }
        }()
        case 13: try { try decoder.decodeRepeatedEnumField(value: &_storage._networks) }()
        case 14: try { try decoder.decodeSingularMessageField(value: &_storage._portList) }()
        case 15: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &_storage._attributes) }()
        case 16: try { try decoder.decodeSingularMessageField(value: &_storage._sourcePortList) }()
        case 17: try { try decoder.decodeRepeatedMessageField(value: &_storage._localIp) }()
        case 18: try { try decoder.decodeSingularMessageField(value: &_storage._localPortList) }()
        case 19: try { try decoder.decodeSingularStringField(value: &_storage._ruleTag) }()
        case 20: try { try decoder.decodeSingularMessageField(value: &_storage._vlessRouteList) }()
        case 21: try { try decoder.decodeRepeatedStringField(value: &_storage._process) }()
        case 22: try { try decoder.decodeSingularMessageField(value: &_storage._webhook) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if case .tag(let v)? = _storage._targetTag {
        try visitor.visitSingularStringField(value: v, fieldNumber: 1)
      } }()
      if !_storage._domain.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._domain, fieldNumber: 2)
      }
      if !_storage._userEmail.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._userEmail, fieldNumber: 7)
      }
      if !_storage._inboundTag.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._inboundTag, fieldNumber: 8)
      }
      if !_storage._protocol.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._protocol, fieldNumber: 9)
      }
      if !_storage._ip.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._ip, fieldNumber: 10)
      }
      if !_storage._sourceIp.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._sourceIp, fieldNumber: 11)
      }
      try { if case .balancingTag(let v)? = _storage._targetTag {
        try visitor.visitSingularStringField(value: v, fieldNumber: 12)
      } }()
      if !_storage._networks.isEmpty {
        try visitor.visitPackedEnumField(value: _storage._networks, fieldNumber: 13)
      }
      try { if let v = _storage._portList {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 14)
      } }()
      if !_storage._attributes.isEmpty {
        try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: _storage._attributes, fieldNumber: 15)
      }
      try { if let v = _storage._sourcePortList {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 16)
      } }()
      if !_storage._localIp.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._localIp, fieldNumber: 17)
      }
      try { if let v = _storage._localPortList {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 18)
      } }()
      if !_storage._ruleTag.isEmpty {
        try visitor.visitSingularStringField(value: _storage._ruleTag, fieldNumber: 19)
      }
      try { if let v = _storage._vlessRouteList {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 20)
      } }()
      if !_storage._process.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._process, fieldNumber: 21)
      }
      try { if let v = _storage._webhook {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 22)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Xray_App_Router_RoutingRule, rhs: Xray_App_Router_RoutingRule) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._targetTag != rhs_storage._targetTag {return false}
        if _storage._ruleTag != rhs_storage._ruleTag {return false}
        if _storage._domain != rhs_storage._domain {return false}
        if _storage._ip != rhs_storage._ip {return false}
        if _storage._portList != rhs_storage._portList {return false}
        if _storage._networks != rhs_storage._networks {return false}
        if _storage._sourceIp != rhs_storage._sourceIp {return false}
        if _storage._sourcePortList != rhs_storage._sourcePortList {return false}
        if _storage._userEmail != rhs_storage._userEmail {return false}
        if _storage._inboundTag != rhs_storage._inboundTag {return false}
        if _storage._protocol != rhs_storage._protocol {return false}
        if _storage._attributes != rhs_storage._attributes {return false}
        if _storage._localIp != rhs_storage._localIp {return false}
        if _storage._localPortList != rhs_storage._localPortList {return false}
        if _storage._vlessRouteList != rhs_storage._vlessRouteList {return false}
        if _storage._process != rhs_storage._process {return false}
        if _storage._webhook != rhs_storage._webhook {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Xray_App_Router_WebhookConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".WebhookConfig"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "url"),
    2: .same(proto: "deduplication"),
    3: .same(proto: "headers"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.url) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.deduplication) }()
      case 3: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.headers) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.url.isEmpty {
      try visitor.visitSingularStringField(value: self.url, fieldNumber: 1)
    }
    if self.deduplication != 0 {
      try visitor.visitSingularUInt32Field(value: self.deduplication, fieldNumber: 2)
    }
    if !self.headers.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.headers, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Xray_App_Router_WebhookConfig, rhs: Xray_App_Router_WebhookConfig) -> Bool {
    if lhs.url != rhs.url {return false}
    if lhs.deduplication != rhs.deduplication {return false}
    if lhs.headers != rhs.headers {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Xray_App_Router_BalancingRule: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BalancingRule"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "tag"),
    2: .standard(proto: "outbound_selector"),
    3: .same(proto: "strategy"),
    4: .standard(proto: "strategy_settings"),
    5: .standard(proto: "fallback_tag"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.tag) }()
      case 2: try { try decoder.decodeRepeatedStringField(value: &self.outboundSelector) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.strategy) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._strategySettings) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.fallbackTag) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.tag.isEmpty {
      try visitor.visitSingularStringField(value: self.tag, fieldNumber: 1)
    }
    if !self.outboundSelector.isEmpty {
      try visitor.visitRepeatedStringField(value: self.outboundSelector, fieldNumber: 2)
    }
    if !self.strategy.isEmpty {
      try visitor.visitSingularStringField(value: self.strategy, fieldNumber: 3)
    }
    try { if let v = self._strategySettings {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    if !self.fallbackTag.isEmpty {
      try visitor.visitSingularStringField(value: self.fallbackTag, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Xray_App_Router_BalancingRule, rhs: Xray_App_Router_BalancingRule) -> Bool {
    if lhs.tag != rhs.tag {return false}
    if lhs.outboundSelector != rhs.outboundSelector {return false}
    if lhs.strategy != rhs.strategy {return false}
    if lhs._strategySettings != rhs._strategySettings {return false}
    if lhs.fallbackTag != rhs.fallbackTag {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Xray_App_Router_StrategyWeight: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StrategyWeight"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "regexp"),
    2: .same(proto: "match"),
    3: .same(proto: "value"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.regexp) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.match) }()
      case 3: try { try decoder.decodeSingularFloatField(value: &self.value) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.regexp != false {
      try visitor.visitSingularBoolField(value: self.regexp, fieldNumber: 1)
    }
    if !self.match.isEmpty {
      try visitor.visitSingularStringField(value: self.match, fieldNumber: 2)
    }
    if self.value.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.value, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Xray_App_Router_StrategyWeight, rhs: Xray_App_Router_StrategyWeight) -> Bool {
    if lhs.regexp != rhs.regexp {return false}
    if lhs.match != rhs.match {return false}
    if lhs.value != rhs.value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Xray_App_Router_StrategyLeastLoadConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StrategyLeastLoadConfig"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    2: .same(proto: "costs"),
    3: .same(proto: "baselines"),
    4: .same(proto: "expected"),
    5: .same(proto: "maxRTT"),
    6: .same(proto: "tolerance"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.costs) }()
      case 3: try { try decoder.decodeRepeatedInt64Field(value: &self.baselines) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.expected) }()
      case 5: try { try decoder.decodeSingularInt64Field(value: &self.maxRtt) }()
      case 6: try { try decoder.decodeSingularFloatField(value: &self.tolerance) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.costs.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.costs, fieldNumber: 2)
    }
    if !self.baselines.isEmpty {
      try visitor.visitPackedInt64Field(value: self.baselines, fieldNumber: 3)
    }
    if self.expected != 0 {
      try visitor.visitSingularInt32Field(value: self.expected, fieldNumber: 4)
    }
    if self.maxRtt != 0 {
      try visitor.visitSingularInt64Field(value: self.maxRtt, fieldNumber: 5)
    }
    if self.tolerance.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.tolerance, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Xray_App_Router_StrategyLeastLoadConfig, rhs: Xray_App_Router_StrategyLeastLoadConfig) -> Bool {
    if lhs.costs != rhs.costs {return false}
    if lhs.baselines != rhs.baselines {return false}
    if lhs.expected != rhs.expected {return false}
    if lhs.maxRtt != rhs.maxRtt {return false}
    if lhs.tolerance != rhs.tolerance {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Xray_App_Router_Config: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Config"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "domain_strategy"),
    2: .same(proto: "rule"),
    3: .standard(proto: "balancing_rule"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.domainStrategy) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.rule) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.balancingRule) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.domainStrategy != .asIs {
      try visitor.visitSingularEnumField(value: self.domainStrategy, fieldNumber: 1)
    }
    if !self.rule.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.rule, fieldNumber: 2)
    }
    if !self.balancingRule.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.balancingRule, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Xray_App_Router_Config, rhs: Xray_App_Router_Config) -> Bool {
    if lhs.domainStrategy != rhs.domainStrategy {return false}
    if lhs.rule != rhs.rule {return false}
    if lhs.balancingRule != rhs.balancingRule {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Xray_App_Router_Config.DomainStrategy: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "AsIs"),
    2: .same(proto: "IpIfNonMatch"),
    3: .same(proto: "IpOnDemand"),
  ]
}
