// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: proxy/dokodemo/config.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct Xray_Proxy_Dokodemo_Config: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var address: Xray_Common_Net_IPOrDomain {
    get {return _address ?? Xray_Common_Net_IPOrDomain()}
    set {_address = newValue}
  }
  /// Returns true if `address` has been explicitly set.
  public var hasAddress: Bool {return self._address != nil}
  /// Clears the value of `address`. Subsequent reads from it will return its default value.
  public mutating func clearAddress() {self._address = nil}

  public var port: UInt32 = 0

  /// List of networks that the Dokodemo accepts.
  public var networks: [Xray_Common_Net_Network] = []

  public var followRedirect: Bool = false

  public var userLevel: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _address: Xray_Common_Net_IPOrDomain? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "xray.proxy.dokodemo"

extension Xray_Proxy_Dokodemo_Config: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Config"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "address"),
    2: .same(proto: "port"),
    7: .same(proto: "networks"),
    5: .standard(proto: "follow_redirect"),
    6: .standard(proto: "user_level"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._address) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.port) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.followRedirect) }()
      case 6: try { try decoder.decodeSingularUInt32Field(value: &self.userLevel) }()
      case 7: try { try decoder.decodeRepeatedEnumField(value: &self.networks) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._address {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if self.port != 0 {
      try visitor.visitSingularUInt32Field(value: self.port, fieldNumber: 2)
    }
    if self.followRedirect != false {
      try visitor.visitSingularBoolField(value: self.followRedirect, fieldNumber: 5)
    }
    if self.userLevel != 0 {
      try visitor.visitSingularUInt32Field(value: self.userLevel, fieldNumber: 6)
    }
    if !self.networks.isEmpty {
      try visitor.visitPackedEnumField(value: self.networks, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Xray_Proxy_Dokodemo_Config, rhs: Xray_Proxy_Dokodemo_Config) -> Bool {
    if lhs._address != rhs._address {return false}
    if lhs.port != rhs.port {return false}
    if lhs.networks != rhs.networks {return false}
    if lhs.followRedirect != rhs.followRedirect {return false}
    if lhs.userLevel != rhs.userLevel {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
