// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: proxy/vless/inbound/config.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct Xray_Proxy_Vless_Inbound_Fallback: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var name: String = String()

  public var alpn: String = String()

  public var path: String = String()

  public var type: String = String()

  public var dest: String = String()

  public var xver: UInt64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Xray_Proxy_Vless_Inbound_Config: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var clients: [Xray_Common_Protocol_User] = []

  /// Decryption settings. Only applies to server side, and only accepts "none"
  /// for now.
  public var decryption: String = String()

  public var fallbacks: [Xray_Proxy_Vless_Inbound_Fallback] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "xray.proxy.vless.inbound"

extension Xray_Proxy_Vless_Inbound_Fallback: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Fallback"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "name"),
    2: .same(proto: "alpn"),
    3: .same(proto: "path"),
    4: .same(proto: "type"),
    5: .same(proto: "dest"),
    6: .same(proto: "xver"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.alpn) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.path) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.type) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.dest) }()
      case 6: try { try decoder.decodeSingularUInt64Field(value: &self.xver) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.alpn.isEmpty {
      try visitor.visitSingularStringField(value: self.alpn, fieldNumber: 2)
    }
    if !self.path.isEmpty {
      try visitor.visitSingularStringField(value: self.path, fieldNumber: 3)
    }
    if !self.type.isEmpty {
      try visitor.visitSingularStringField(value: self.type, fieldNumber: 4)
    }
    if !self.dest.isEmpty {
      try visitor.visitSingularStringField(value: self.dest, fieldNumber: 5)
    }
    if self.xver != 0 {
      try visitor.visitSingularUInt64Field(value: self.xver, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Xray_Proxy_Vless_Inbound_Fallback, rhs: Xray_Proxy_Vless_Inbound_Fallback) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.alpn != rhs.alpn {return false}
    if lhs.path != rhs.path {return false}
    if lhs.type != rhs.type {return false}
    if lhs.dest != rhs.dest {return false}
    if lhs.xver != rhs.xver {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Xray_Proxy_Vless_Inbound_Config: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Config"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "clients"),
    2: .same(proto: "decryption"),
    3: .same(proto: "fallbacks"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.clients) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.decryption) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.fallbacks) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.clients.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.clients, fieldNumber: 1)
    }
    if !self.decryption.isEmpty {
      try visitor.visitSingularStringField(value: self.decryption, fieldNumber: 2)
    }
    if !self.fallbacks.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.fallbacks, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Xray_Proxy_Vless_Inbound_Config, rhs: Xray_Proxy_Vless_Inbound_Config) -> Bool {
    if lhs.clients != rhs.clients {return false}
    if lhs.decryption != rhs.decryption {return false}
    if lhs.fallbacks != rhs.fallbacks {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
