// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: proxy/freedom/config.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct Xray_Proxy_Freedom_DestinationOverride: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var server: Xray_Common_Protocol_ServerEndpoint {
    get {return _server ?? Xray_Common_Protocol_ServerEndpoint()}
    set {_server = newValue}
  }
  /// Returns true if `server` has been explicitly set.
  public var hasServer: Bool {return self._server != nil}
  /// Clears the value of `server`. Subsequent reads from it will return its default value.
  public mutating func clearServer() {self._server = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _server: Xray_Common_Protocol_ServerEndpoint? = nil
}

public struct Xray_Proxy_Freedom_Fragment: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var packetsFrom: UInt64 = 0

  public var packetsTo: UInt64 = 0

  public var lengthMin: UInt64 = 0

  public var lengthMax: UInt64 = 0

  public var intervalMin: UInt64 = 0

  public var intervalMax: UInt64 = 0

  public var maxSplitMin: UInt64 = 0

  public var maxSplitMax: UInt64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Xray_Proxy_Freedom_Noise: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var lengthMin: UInt64 = 0

  public var lengthMax: UInt64 = 0

  public var delayMin: UInt64 = 0

  public var delayMax: UInt64 = 0

  public var packet: Data = Data()

  public var applyTo: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Xray_Proxy_Freedom_Config: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var domainStrategy: Xray_Transport_Internet_DomainStrategy {
    get {return _storage._domainStrategy}
    set {_uniqueStorage()._domainStrategy = newValue}
  }

  public var destinationOverride: Xray_Proxy_Freedom_DestinationOverride {
    get {return _storage._destinationOverride ?? Xray_Proxy_Freedom_DestinationOverride()}
    set {_uniqueStorage()._destinationOverride = newValue}
  }
  /// Returns true if `destinationOverride` has been explicitly set.
  public var hasDestinationOverride: Bool {return _storage._destinationOverride != nil}
  /// Clears the value of `destinationOverride`. Subsequent reads from it will return its default value.
  public mutating func clearDestinationOverride() {_uniqueStorage()._destinationOverride = nil}

  public var userLevel: UInt32 {
    get {return _storage._userLevel}
    set {_uniqueStorage()._userLevel = newValue}
  }

  public var fragment: Xray_Proxy_Freedom_Fragment {
    get {return _storage._fragment ?? Xray_Proxy_Freedom_Fragment()}
    set {_uniqueStorage()._fragment = newValue}
  }
  /// Returns true if `fragment` has been explicitly set.
  public var hasFragment: Bool {return _storage._fragment != nil}
  /// Clears the value of `fragment`. Subsequent reads from it will return its default value.
  public mutating func clearFragment() {_uniqueStorage()._fragment = nil}

  public var proxyProtocol: UInt32 {
    get {return _storage._proxyProtocol}
    set {_uniqueStorage()._proxyProtocol = newValue}
  }

  public var noises: [Xray_Proxy_Freedom_Noise] {
    get {return _storage._noises}
    set {_uniqueStorage()._noises = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "xray.proxy.freedom"

extension Xray_Proxy_Freedom_DestinationOverride: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DestinationOverride"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "server"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._server) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._server {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Xray_Proxy_Freedom_DestinationOverride, rhs: Xray_Proxy_Freedom_DestinationOverride) -> Bool {
    if lhs._server != rhs._server {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Xray_Proxy_Freedom_Fragment: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Fragment"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "packets_from"),
    2: .standard(proto: "packets_to"),
    3: .standard(proto: "length_min"),
    4: .standard(proto: "length_max"),
    5: .standard(proto: "interval_min"),
    6: .standard(proto: "interval_max"),
    7: .standard(proto: "max_split_min"),
    8: .standard(proto: "max_split_max"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.packetsFrom) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.packetsTo) }()
      case 3: try { try decoder.decodeSingularUInt64Field(value: &self.lengthMin) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self.lengthMax) }()
      case 5: try { try decoder.decodeSingularUInt64Field(value: &self.intervalMin) }()
      case 6: try { try decoder.decodeSingularUInt64Field(value: &self.intervalMax) }()
      case 7: try { try decoder.decodeSingularUInt64Field(value: &self.maxSplitMin) }()
      case 8: try { try decoder.decodeSingularUInt64Field(value: &self.maxSplitMax) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.packetsFrom != 0 {
      try visitor.visitSingularUInt64Field(value: self.packetsFrom, fieldNumber: 1)
    }
    if self.packetsTo != 0 {
      try visitor.visitSingularUInt64Field(value: self.packetsTo, fieldNumber: 2)
    }
    if self.lengthMin != 0 {
      try visitor.visitSingularUInt64Field(value: self.lengthMin, fieldNumber: 3)
    }
    if self.lengthMax != 0 {
      try visitor.visitSingularUInt64Field(value: self.lengthMax, fieldNumber: 4)
    }
    if self.intervalMin != 0 {
      try visitor.visitSingularUInt64Field(value: self.intervalMin, fieldNumber: 5)
    }
    if self.intervalMax != 0 {
      try visitor.visitSingularUInt64Field(value: self.intervalMax, fieldNumber: 6)
    }
    if self.maxSplitMin != 0 {
      try visitor.visitSingularUInt64Field(value: self.maxSplitMin, fieldNumber: 7)
    }
    if self.maxSplitMax != 0 {
      try visitor.visitSingularUInt64Field(value: self.maxSplitMax, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Xray_Proxy_Freedom_Fragment, rhs: Xray_Proxy_Freedom_Fragment) -> Bool {
    if lhs.packetsFrom != rhs.packetsFrom {return false}
    if lhs.packetsTo != rhs.packetsTo {return false}
    if lhs.lengthMin != rhs.lengthMin {return false}
    if lhs.lengthMax != rhs.lengthMax {return false}
    if lhs.intervalMin != rhs.intervalMin {return false}
    if lhs.intervalMax != rhs.intervalMax {return false}
    if lhs.maxSplitMin != rhs.maxSplitMin {return false}
    if lhs.maxSplitMax != rhs.maxSplitMax {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Xray_Proxy_Freedom_Noise: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Noise"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "length_min"),
    2: .standard(proto: "length_max"),
    3: .standard(proto: "delay_min"),
    4: .standard(proto: "delay_max"),
    5: .same(proto: "packet"),
    6: .standard(proto: "apply_to"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.lengthMin) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.lengthMax) }()
      case 3: try { try decoder.decodeSingularUInt64Field(value: &self.delayMin) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self.delayMax) }()
      case 5: try { try decoder.decodeSingularBytesField(value: &self.packet) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.applyTo) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.lengthMin != 0 {
      try visitor.visitSingularUInt64Field(value: self.lengthMin, fieldNumber: 1)
    }
    if self.lengthMax != 0 {
      try visitor.visitSingularUInt64Field(value: self.lengthMax, fieldNumber: 2)
    }
    if self.delayMin != 0 {
      try visitor.visitSingularUInt64Field(value: self.delayMin, fieldNumber: 3)
    }
    if self.delayMax != 0 {
      try visitor.visitSingularUInt64Field(value: self.delayMax, fieldNumber: 4)
    }
    if !self.packet.isEmpty {
      try visitor.visitSingularBytesField(value: self.packet, fieldNumber: 5)
    }
    if !self.applyTo.isEmpty {
      try visitor.visitSingularStringField(value: self.applyTo, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Xray_Proxy_Freedom_Noise, rhs: Xray_Proxy_Freedom_Noise) -> Bool {
    if lhs.lengthMin != rhs.lengthMin {return false}
    if lhs.lengthMax != rhs.lengthMax {return false}
    if lhs.delayMin != rhs.delayMin {return false}
    if lhs.delayMax != rhs.delayMax {return false}
    if lhs.packet != rhs.packet {return false}
    if lhs.applyTo != rhs.applyTo {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Xray_Proxy_Freedom_Config: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Config"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "domain_strategy"),
    3: .standard(proto: "destination_override"),
    4: .standard(proto: "user_level"),
    5: .same(proto: "fragment"),
    6: .standard(proto: "proxy_protocol"),
    7: .same(proto: "noises"),
  ]

  fileprivate class _StorageClass {
    var _domainStrategy: Xray_Transport_Internet_DomainStrategy = .asIs
    var _destinationOverride: Xray_Proxy_Freedom_DestinationOverride? = nil
    var _userLevel: UInt32 = 0
    var _fragment: Xray_Proxy_Freedom_Fragment? = nil
    var _proxyProtocol: UInt32 = 0
    var _noises: [Xray_Proxy_Freedom_Noise] = []

    #if swift(>=5.10)
      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()
    #else
      static let defaultInstance = _StorageClass()
    #endif

    private init() {}

    init(copying source: _StorageClass) {
      _domainStrategy = source._domainStrategy
      _destinationOverride = source._destinationOverride
      _userLevel = source._userLevel
      _fragment = source._fragment
      _proxyProtocol = source._proxyProtocol
      _noises = source._noises
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularEnumField(value: &_storage._domainStrategy) }()
        case 3: try { try decoder.decodeSingularMessageField(value: &_storage._destinationOverride) }()
        case 4: try { try decoder.decodeSingularUInt32Field(value: &_storage._userLevel) }()
        case 5: try { try decoder.decodeSingularMessageField(value: &_storage._fragment) }()
        case 6: try { try decoder.decodeSingularUInt32Field(value: &_storage._proxyProtocol) }()
        case 7: try { try decoder.decodeRepeatedMessageField(value: &_storage._noises) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if _storage._domainStrategy != .asIs {
        try visitor.visitSingularEnumField(value: _storage._domainStrategy, fieldNumber: 1)
      }
      try { if let v = _storage._destinationOverride {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      } }()
      if _storage._userLevel != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._userLevel, fieldNumber: 4)
      }
      try { if let v = _storage._fragment {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      } }()
      if _storage._proxyProtocol != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._proxyProtocol, fieldNumber: 6)
      }
      if !_storage._noises.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._noises, fieldNumber: 7)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Xray_Proxy_Freedom_Config, rhs: Xray_Proxy_Freedom_Config) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._domainStrategy != rhs_storage._domainStrategy {return false}
        if _storage._destinationOverride != rhs_storage._destinationOverride {return false}
        if _storage._userLevel != rhs_storage._userLevel {return false}
        if _storage._fragment != rhs_storage._fragment {return false}
        if _storage._proxyProtocol != rhs_storage._proxyProtocol {return false}
        if _storage._noises != rhs_storage._noises {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
