// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: transport/internet/tcp/config.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct Xray_Transport_Internet_Tcp_Config: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var headerSettings: Xray_Common_Serial_TypedMessage {
    get {return _headerSettings ?? Xray_Common_Serial_TypedMessage()}
    set {_headerSettings = newValue}
  }
  /// Returns true if `headerSettings` has been explicitly set.
  public var hasHeaderSettings: Bool {return self._headerSettings != nil}
  /// Clears the value of `headerSettings`. Subsequent reads from it will return its default value.
  public mutating func clearHeaderSettings() {self._headerSettings = nil}

  public var acceptProxyProtocol: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _headerSettings: Xray_Common_Serial_TypedMessage? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "xray.transport.internet.tcp"

extension Xray_Transport_Internet_Tcp_Config: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Config"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    2: .standard(proto: "header_settings"),
    3: .standard(proto: "accept_proxy_protocol"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 2: try { try decoder.decodeSingularMessageField(value: &self._headerSettings) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.acceptProxyProtocol) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._headerSettings {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if self.acceptProxyProtocol != false {
      try visitor.visitSingularBoolField(value: self.acceptProxyProtocol, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Xray_Transport_Internet_Tcp_Config, rhs: Xray_Transport_Internet_Tcp_Config) -> Bool {
    if lhs._headerSettings != rhs._headerSettings {return false}
    if lhs.acceptProxyProtocol != rhs.acceptProxyProtocol {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
